### ISSUE TITLE
SearchView not expanding always

### ISSUE THREAD

**Issue by AngleV** [lapism/SearchView#1]
if i tap to expand the view a few times it does not show up always.
i can see the dimming and the soft keyboard but not the view

**Comment by lapism** [comment]
Hi, I found this bug today too :-p. I think It is problem with Reveal animation on API 21+, but I have never tried this on lower API.  It will be fixed till Monday.

**Comment by AngleV** [comment]
Yes i can confirm that its the reveal animation.
Keep in mind that i am testing it on a real device with API 22

**Comment by lapism** [comment]
fixed in version 1.1.2 :)

**Comment by AngleV** [comment]
was it necessary to remove the setOnSearchViewListener 

i need to know when the user close the view 

```
 @Override
 public void onSearchViewClosed() { }
```

**Comment by lapism** [comment]
It will be back very soon.
