### ISSUE TITLE
How to open IME when Activity onCreate()？

### ISSUE THREAD

**Issue by Andecy** [lapism/SearchView#103]
```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        //...
        setSearchView();//like sample
        mSearchView.open(false);
    }
```

but the IME does not appear,It also need to click the EditText.

the SearchView.Version is toolbar_icon

**Comment by lapism** [comment]
Hi, you do not need SearchView.open for TOOLBAR_ICON. It is only for MENU ITEM. just place searchview in your xml and use findviewbyid method in your activity.

**Comment by Andecy** [comment]
@lapism I just want to Open IME when Activity is onCreate

**Comment by alirezaafkar** [comment]
@lapism I think it's good to make showKeyboard and hideKeyboard public

**Comment by Andecy** [comment]
@alirezaafkar Yes but the public method need EditText

**Comment by Andecy** [comment]
@alirezaafkar Yes but the public method need EditText

**Comment by lapism** [comment]
You can use addFocus and removeFocus. For next version I am gonna change those two methods to public.

**Comment by Andecy** [comment]
@lapism I try to call the method，but it does not work

**Comment by lapism** [comment]
Ok, then I will open those two methods. Today or Tomorrow will be 3.3.1.

**Comment by lapism** [comment]
3.3.1 is out. And for me SearchView.open(false) adds focus to view with keyboard. Check sample project, I have added to ResultActivity example.

**Comment by Andecy** [comment]
Thanks,It's better for using
