### ISSUE TITLE
Error in sample app

### ISSUE THREAD

**Issue by benoffi7** [lapism/SearchView#104]
1) Open the app
2) Click in the searchview
3) Click the backbutton in the search view <- does not work

When I click it should close the search view and the keyboard.

Also the close keyboard key (the triangule key) does not working. the circle button (home) and the square (recents apps) yes.

**Comment by lapism** [comment]
Set openCloseListener.

**Comment by lapism** [comment]
And check please sample project. There is the reason why I dit it.

**Comment by lapism** [comment]
Or. If you mean sample project then that is only quick sample for showing capabilities of the library.

**Comment by lapism** [comment]
Use navigation drawer to show toolbar or menu item activity.

**Comment by lapism** [comment]
OK. So I found out that there is an error in Sample App. I will fix it soon.

**Comment by ivamluz** [comment]
@lapism, I think this is fixed already, no?

**Comment by lapism** [comment]
No. He means something else. Architecture if the sample needs using onPostCreate for SearchView. But it is just a sample...
