### ISSUE TITLE
Size of HistoryList

### ISSUE THREAD

**Issue by Andecy** [lapism/SearchView#107]
How to change size of historyList?

2 for now

**Comment by lapism** [comment]
It is not accessible now. I have not thought that some one of you will ever need it.

**Comment by Andecy** [comment]
It's useful for devices such large screen phone or pad

**Comment by lapism** [comment]
And I have only mobile phone :P. I will try to do something with it in next version.

**Comment by Andecy** [comment]
of course a man  probably has one phone but for different users ,the situation should be changed,thanks you very much :laughing:

**Comment by lapism** [comment]
SearchHistoryTable.setHistorySize(int historySize) will be available in 3.4.

**Comment by Andecy** [comment]
thank you for enhancement
