### ISSUE TITLE
Animation callbacks aren't triggered on close

### ISSUE THREAD

**Issue by ivamluz** [lapism/SearchView#109]
Tested on two devices (Samsung S3 and a Nexus) running Android 4.3.

The animation callbacks arent't triggered and, by consequence, isn't the close callback as well.

**Comment by lapism** [comment]
Have you tried a last version ? I do not own Android 4.3, but I am going to try it on 4.4.

**Comment by ivamluz** [comment]
Didn't try on 3.3.2. Gonna try it today, probably.

If that's still an issue, I'll try to fix it and submit a pull request this week, since this is critical for the project I'm working on.

**Comment by lapism** [comment]
I do not know because I need to try it. But there are callback in Animator, so It should work. But like I said I need to check it.

**Comment by lapism** [comment]
And why not, I am open to every pull requests.

**Comment by ivamluz** [comment]
Yes. I saw the callbacks are defined, but they are never called when I set a breakpoint on them and test on Android 4.3 devices.

I'll let you know once I have more information.

**Comment by ivamluz** [comment]
Things I noticed so far:

1. Callbacks work ok on sample app, but not inside my actual app (still investigating, but it's being hard to find out what's happening);
2. If I call view.clearAnimation(); inside the onAnimationEnd() callbacks for fadeClose()/fadeOpen(), it works as expected in my application.

Any thoughts?

**Comment by lapism** [comment]
And callbacks are working in your app for 5.0+? I still need to check the functionality on KitKat.

**Comment by ivamluz** [comment]
The scenarios is the following:

- On sample app, the callbacks (both for opening and closing) are properly called on Androids 4.x and 6.x (didn't test on 5.x);
- On my app, the callbacks are always called on Android 6.x, but only the open callback is called on Android 4.x

**Comment by lapism** [comment]
So it looks like an error on your side, but I am not really sure. 
If you find out where is a problem then please let me know if something must be changed in SearchAnimator.

**Comment by ivamluz** [comment]
Yeah, I think that's on my side.

For now, we are referencing our forked version (calling clearAnimations() on onAnimationEnd()).

I'll get back to it when I have time and let you know what I could find.

**Comment by lapism** [comment]
It is working on Kit Kat :).
