### ISSUE TITLE
Microphone not visible

### ISSUE THREAD

**Issue by EpsilonOrionis** [lapism/SearchView#11]
Hi, I implemented your library and it's awesome, but when I use it on my smartphone, I can't the microphone button. Insted when I test it on my tablet I can see it

**Comment by lapism** [comment]
Hi, thanks a lot. Have you tried to set mSearchView.setVoiceSearch(true) ? Which tablet are you using?

**Comment by EpsilonOrionis** [comment]
Sure, the code that it's on the tablet and on the smartphone is the same. Android Jelly Bean API 17 both.
Latest version of your library. And I use mSearchView.setVoiceSearch(true) as you wrote in your sample.

**Comment by lapism** [comment]
Weird. While ago I've tried sample from Google Store on Kit Kat tablet and it is working fine. Everything is visible. Can you send me version of your tablet, manufacturer, type , resolution of display ?

**Comment by EpsilonOrionis** [comment]
Samsung gts7580

**Comment by lapism** [comment]
Thanks. I will borrow some device with older API soon, because right now I have no idea why you do not see microphone on different devices with same version of API 17.

**Comment by EpsilonOrionis** [comment]
Ok thank you, let me know :)

**Comment by lapism** [comment]
Of course, I will :)

**Comment by lapism** [comment]
Sorry, but I was not able to get some old devices ... everything is working fine with my testing devices with API 19, 21, 22 and 23.

**Comment by EpsilonOrionis** [comment]
Ok, so problem solved?

**Comment by lapism** [comment]
Not really. I checked dimension for XML and code, tried it on tablets and cellphones and I am not really sure what happened with your device. So check your code again and be sure it is same for both. Maybe in future I will get some JB device, but for now everything seems OK.

**Comment by EpsilonOrionis** [comment]
Ok man, no problem ;)

**Comment by lapism** [comment]
I found out finally why you have had a problem with MIC. It will be fixed in next BIG version :).
