### ISSUE TITLE
When search view is opened and device gets rotated, search view is wrongly submitted

### ISSUE THREAD

**Issue by ivamluz** [lapism/SearchView#113]
Steps to reproduce:
1. Configure search view as toolbar;
2. Open search view and type a text;
3. Rotate device.

Instead of staying in the same activity and keeping the search opened, the search is submitted and the search results activity is opened.

**Comment by lapism** [comment]
interesting. It will be a bug somewhere :D. But I do not have time to fix anything till August.

**Comment by ivamluz** [comment]
No worries. I'll have to fix it somehow until the end of this week lol

**Comment by lapism** [comment]
I will give you credits in README later. Thank you very much for improving this library. Till August I will only release new versions with pull requests and bugfixes.

**Comment by ivamluz** [comment]
No, thank you for making this open :+1:
