### ISSUE TITLE
Custom Adapter

### ISSUE THREAD

**Issue by luisvega16** [lapism/SearchView#115]
Hi,

Can I create a custom adapter for the SearchView? Because I'm trying to create an adapter extending the SearchAdapter, but I couldn't.  I just want the results as the search results in the Messenger app of Google. Another problem is that the results are show in lower case. :/

I'm using the 3.3.2 version.

**Comment by ivamluz** [comment]
@luisvega16, SearchView class has two overloaded methods for setting adapters:

```
    // ---------------------------------------------------------------------------------------------
    public void setAdapter(SearchAdapter adapter) {
        mSearchAdapter = adapter;
        mRecyclerView.setAdapter(mSearchAdapter);
    }

    @SuppressWarnings("unused")
    public void setAdapter(RecyclerView.Adapter adapter) {
        mAdapter = adapter;
        mRecyclerView.setAdapter(mAdapter);
    }
```

I think you can you the one that accepts an instance of RecyclerView.Adapter to do what you want. We are using this version in the app we use the library and it works pretty well.

**Comment by luisvega16** [comment]
@ivamluz I already tried to use that method using an adapter extending the RecyclerView.Adapter, but nothing was showing in the results. But If you say that you used that method and works, then I will try it again, maybe something I'm doing wrong.

**Comment by lapism** [comment]
Yes, @ivamluz is right. You should use those two methods.

**Comment by luisvega16** [comment]
Thanks @ivamluz  and @lapism I created a full custom adapter and is working. Great work guys! ;)

**Comment by lapism** [comment]
you are welcome :)

**Comment by JulienRaad** [comment]
Hello guys, i have the same issue. I just can't see the results when using custom adapter. How can this be solved ?

**Comment by lapism** [comment]
I have to check it because maybe that is a bug :-).

**Comment by JulienRaad** [comment]
Results are not visible and sometimes the search view fails to show in dim mode when clicked and using a custom adapter. Is there a way to do it with the SearchAdapter and use custom view holder ?
