### ISSUE TITLE
Support for targetSdkVersion < 23 and compileSdkVersion < 23 

### ISSUE THREAD

**Issue by Jayiitb** [lapism/SearchView#12]
Not able to use your library for targetSdkVersion = 21 and compileSdkVersion = 21

**Comment by lapism** [comment]
Any reason WHY you are using this ?
Library has the newest dependencies 23.1.1 + 
    compileSdkVersion 23
    buildToolsVersion "23.0.2"
    minSdkVersion 14
    targetSdkVersion 23
    Gradle 1.5.0
  
And you should have the same ...
