### ISSUE TITLE
Bug on screen rotation with opened SearchView (v.3.4)

### ISSUE THREAD

**Issue by ultraon** [lapism/SearchView#125]
Hello, i found bug with SearchView v.3.4. Try in the example application to open SearchView, type some letters and rotate screen, after restoring state the onSubmitQuery(...) is called (onRestoreInstanceState() -> setQuery(...) -> onSubmitQuery(...)), in the result we have search result Activity opened. To fix it replace setQuery() line #901 with setText() I think.

**Comment by ivamluz** [comment]
This is duplicated of #113.

**Comment by ultraon** [comment]
Agree.

**Comment by lapism** [comment]
Fix will be available in next version in August.
