### ISSUE TITLE
How to add this library in a Fragment

### ISSUE THREAD

**Issue by Abo-Hani** [lapism/SearchView#127]
Hi,
My question might be a bit "noobie", but i tried the steps, and checked the sample, it's really hard to understand, not to mention the 2-steps guide .

What's the way to add this library in a fragment ?

**Comment by lapism** [comment]
Same like in Activity, but you should set method setVoice(true, fragment) for voice searching.

**Comment by Abo-Hani** [comment]
I've added it in a fragment, but the problem i'm having is the MaterialSearch isn't visible at all, when i press the search icon, nothing happen, if though i put the mSearchview.open(true), but when i put the query and submit it, the MaterialSearchview shows under the toolbar along with the query, but i can't modify the query or press the "X" icon.

**Comment by lapism** [comment]
I do not know. It is not a bug in library but error in your xml layout probably because every Fragment has own layout.

**Comment by lapism** [comment]
And try to set mSearchView.setShadow to false.

**Comment by Abo-Hani** [comment]
Hi again, I've managed to make in a fragment, but i'm having the following "problems" or kida problems : 
- When you press the search icon, the material searchview animation start from a different ActionBar icon, it should start from the clicked icon, but it's starting from the 3dots icon (menu), same for closing animation .
- there's a gap in the left and right, when you press on the left, the Navigation Menu open (slider), i should be a way to block that from happening ?

**Comment by lapism** [comment]
Hi.

1. Yes, it should. But I did not find the way how to fix it. I have idea with menu position. It is in my TODO list, do not worry.

**Comment by lapism** [comment]
What gap?

**Comment by Abo-Hani** [comment]
@lapism there's a gap, the margin, when you click that space, you can click the background options, i had to do this code changes to stop the background clicks : 

        if (mVersion == VERSION_MENU_ITEM) {
            setVisibility(View.VISIBLE);
            if (animate) {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                    reveal();
                } else {
                    SearchAnimator.fadeOpen(mCardView, mAnimationDuration, mEditText, mShouldClearOnOpen, mOnOpenCloseListener);
                }


            } else {
                mCardView.setVisibility(View.VISIBLE);

                if (mShouldClearOnOpen && mEditText.length() > 0) {
                    mEditText.getText().clear();
                }
                mEditText.requestFocus();
                if (mOnOpenCloseListener != null) {
                    mOnOpenCloseListener.onOpen();
                }
            }
            Handler handler = new Handler();
            handler.postDelayed(new Runnable() {
                @Override
                public void run() {
                    getViewLayout().setVisibility(View.VISIBLE);
                    getViewLayout().setBackgroundColor(getPrimaryColor());
                }
            },1000);

        }

**Comment by Abo-Hani** [comment]
More explaination : 
- When you click the white edittext space, you can click the invisible background menu options, it's really annoying, but this "fix" make it work, also you need to set "isSearchOpen" before you set Visible to the view, to make sure the search is open and closed after that 1000 ms . 

But, i'm having this problem .. i really don't know why those problems pop-up on me :( . The following screenshot shows that the SearchView displayed on the toolbar Visible, the problem that i didn't click any icon to make it open, it's open already without opening it .

http://i.imgur.com/8Q9Bt5w.png

I've tried to setVisiblity to Gone, but it still there! 

My layout : 

     <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
     xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context="com.abohani.ramadantime.MainActivity">



    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:background="?attr/colorPrimary"
        app:layout_scrollFlags="scroll|enterAlways|snap"
        android:minHeight="@dimen/abc_action_bar_default_height_material"
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

    <View
        android:id="@+id/views"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:clickable="true"
        android:visibility="invisible"
        />

    <com.lapism.searchview.SearchView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="?attr/actionBarSize"
        android:visibility="gone"
        />


    <FrameLayout
        android:id="@+id/fragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?framelayoutbg"
        android:layout_alignParentBottom="true"
        android:layout_below="@+id/toolbar" />



    </RelativeLayout>
