### ISSUE TITLE
SearchView does not display suggestions correctly

### ISSUE THREAD

**Issue by namnx** [lapism/SearchView#128]
If a suggestion search item contains the key, it will be displayed in lowercase.
I think in SearchAdapter.java, these lines:
```
String string = item.get_text().toString().toLowerCase(Locale.getDefault());
if (string.contains(key) && !key.isEmpty()) {
    SpannableString s = new SpannableString(string);
    ....
```
should be changed to:
```
String string = item.get_text().toString().toLowerCase(Locale.getDefault());
if (string.contains(key) && !key.isEmpty()) {
    SpannableString s = new SpannableString(item.get_text());
    ....
```

**Comment by ivamluz** [comment]
@namnx, I checked the behavior of Google Play app (from which I think @lapism got inspired to create this lib) and the behavior seems to be the same (display suggestions all in lower case), so I think this is the expected behavior for the lib.

**Comment by lapism** [comment]
and of course it is expected behavior :)
