### ISSUE TITLE
IllegalStateException 

### ISSUE THREAD

**Issue by zheanzy16** [lapism/SearchView#129]
I've been puzzled for days now as to why my app kept on throwing illegalstatexeception only to find that this compiled library was the source.

I'm using gradle 1.5.0 and appcompat 23.2.0, and seems like drawable is being changed to vectordrawble and i'm using a lower sdk version (16)
```
final Drawable d = getDrawable(context, R.drawable.abc_ic_ab_back_material);
        if (d == null || !isVectorDrawable(d)) {
            mHasCheckedVectorDrawableSetup = false;
            throw new IllegalStateException("This app has been built with an incorrect "
                    + "configuration. Please configure your build for VectorDrawableCompat.");
        }
```

any work around in this? thanks

**Comment by lapism** [comment]
I do not know any workaround. Only try to use newer appcompat v24 and gradle 2.1+ with Android Studio.  And let me know.

**Comment by lapism** [comment]
And lib shoulb be compatible with Api 14+.
