### ISSUE TITLE
How to change background color of resultant layout.

### ISSUE THREAD

**Issue by aliansari-powerfulpal** [lapism/SearchView#13]
On Clicking searchview, the background color appear which is almost semi transparent, How can I make it complete transparent. 
![image](https://cloud.githubusercontent.com/assets/13297415/11419967/c32e73f0-944c-11e5-841d-402b28ebdee8.png)

**Comment by Rainer-Lang** [comment]
@aliansari-powerfulpal Just want to know why do you need this? Maybe you have the same need like me.

**Comment by aliansari-powerfulpal** [comment]
Actually I am not showing suggestions, so I just need a to show the searchbar and using onTextChangeListener, I am showing the results in the same fragment.

**Comment by Rainer-Lang** [comment]
YES :-)

**Comment by aliansari-powerfulpal** [comment]
@Rainer-Lang , did you find any solution then?

**Comment by Rainer-Lang** [comment]
Not for now. But I will look today.
Actually the SearchView closes if you/user clicks outside the suggestions - and this should not happen. The SearchView should stay open...

**Comment by aliansari-powerfulpal** [comment]
As for your SearchView closing issue, I am not having that one. I changed the SearchView height to android:layout_height="?attr/actionBarSize" that's why I stays open even if I click anywhere on my page.

**Comment by Rainer-Lang** [comment]
I will try it with your suggestion later. Thanks a lot.
I also will look in the code for the "transparent-issue".

**Comment by Rainer-Lang** [comment]
@aliansari-powerfulpal With your tipp of the height, I have no transparent issue -> all looks like normal.

**Comment by lapism** [comment]
Guys, guys... 
I have done this EXACTLY like in Play Store ( of course without search history, which I hope will be implemented in near future ) so there is no transparent background if SearchView is running.
If you check layout of SearchView in library then you will see View with transparent grey background color with match_parent for width and height. And this View has onClickListener which closes View. Again, same like in Play Store. 
After your click on search text there must be an activity which should handle the searching....and this function is not implemented by library.

**Comment by lapism** [comment]
And if you will use library in your XML layout with android:layout_height = 56dp and not with match_parent, then you can disable the Click Event. It is workaround, but it is working :).

**Comment by Rainer-Lang** [comment]
@lapism Like you suggested I start a new activity and do a search. It works great. Thanks.
