### ISSUE TITLE
[Feature] Add option to add custom item to searchview and setOnNavigationClickListener

### ISSUE THREAD

**Issue by Shnizlon** [lapism/SearchView#131]
It will be great if you could add option to add custom item to searchview like filter for example. Also setOnNavigationClickListener will be great.

**Comment by lapism** [comment]
Hi, Listener for what? You have probably listeners for everything you need. Library is exact copy of what you can see in Play Store so adding more things is not on my priority list now. Maybe in future after I will have more time for developing.

**Comment by Shnizlon** [comment]
Hi, I mean listener for up button in menu item SearchView, I want to override the method to close activity/fragment instead for closing the SearchView. I tried to use open/close listener but the close listener kick in only after animation is finished.

**Comment by lucasfernog** [comment]
OnMenuClickListener does that
