### ISSUE TITLE
Empty Search Suggestion List

### ISSUE THREAD

**Issue by Abo-Hani** [lapism/SearchView#133]
Hi, I'm following your sample app, I've fixed everything to make it work, only one problem and it's the suggestion, my code is as the following : 

   List<SearchItem> suggestionsList = new ArrayList<>();
        Log.i("SearchSuggestion","Size: "+Items.size());

        suggestionsList.add(new SearchItem("search1"));
        SearchAdapter searchAdapter = new SearchAdapter(getActivity(), suggestionsList);
        searchAdapter.setOnItemClickListener(new SearchAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                TextView textView = (TextView) view.findViewById(R.id.textView_item_text);
                String query = textView.getText().toString();
                mSearchView.clearFocus();
                try {
                    Items.clear();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                RvAdapter.notifyDataSetChanged();

                try {
                    MakeConnection2(RvAdapter, query);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        });
        mSearchView.setAdapter(searchAdapter);

But the adapter is empty, the size is 1, but when you type the suggestion text, it won't show .

Info : 
- the app is RTL, maybe it's the problem ?

**Comment by lapism** [comment]
Hi,  library should work with RTL nicely so I am not really sure. Check your code again, u have already one suggestion item.

**Comment by Abo-Hani** [comment]
@lapism I've made a loop for a Json respond, and the size was 50, all in Arabic letters, i've added that 1 item for example, I've tried this : 

        suggestionsList.add(new SearchItem("Search1"));
        suggestionsList.add(new SearchItem("Search2"));
        suggestionsList.add(new SearchItem("Search3"));

still the same, I've the same code as yours, with setSearch and setting the Searchview params and everything.

nothing appears in the suggestion list when i type the first letter, capital or small.

**Comment by Abo-Hani** [comment]
Here's my full SearchView code : 

  mSearchView = (SearchView) ll.findViewById(R.id.searchView);


        if (mSearchView != null) {
            mSearchView.setVersion(SearchView.VERSION_MENU_ITEM);
            mSearchView.setVersionMargins(SearchView.VERSION_MARGINS_MENU_ITEM);
            mSearchView.setTheme(SearchView.THEME_LIGHT,true);
            mSearchView.setHint(R.string.search);
            mSearchView.setTextSize(16);
            mSearchView.setHint("ابحث هنا");
            mSearchView.setDivider(false);
            mSearchView.setVoice(false);
            mSearchView.setAnimationDuration(SearchView.ANIMATION_DURATION);
            mSearchView.setShadow(false);
            mSearchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String query) {
                    mSearchView.clearFocus();
                    try {
                        Items.clear();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    RvAdapter.notifyDataSetChanged();

                    try {
                        MakeConnection2(RvAdapter, query);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    return true;
                }

                @Override
                public boolean onQueryTextChange(String newText) {
                    return false;
                }
            });

            mSearchView.setOnOpenCloseListener(new SearchView.OnOpenCloseListener() {
                @Override
                public void onClose() {
                    if(QquerySubmited) {
                        try {
                            Items.clear();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        RvAdapter.notifyDataSetChanged();
                        try {
                            MakeConnection(RvAdapter);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    }


                    view.setVisibility(View.INVISIBLE);
                }

                @Override
                public void onOpen() {

                }
            });

        }

        List<SearchItem> suggestionsList = new ArrayList<>();
        Log.i("SearchSuggestion","Size: "+Items.size());
        /*
        for (SeriesItem it: Items){
            Log.i("SearchSuggestion",it.getTitle());
            suggestionsList.add(new SearchItem(it.getTitle()));
        }
        */
        suggestionsList.add(new SearchItem("Search1"));
        suggestionsList.add(new SearchItem("Search2"));
        suggestionsList.add(new SearchItem("Search3"));


        SearchAdapter searchAdapter = new SearchAdapter(getActivity(), suggestionsList);
        searchAdapter.setOnItemClickListener(new SearchAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(View view, int position) {
                TextView textView = (TextView) view.findViewById(R.id.textView_item_text);
                String query = textView.getText().toString();
                mSearchView.clearFocus();
                try {
                    Items.clear();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                RvAdapter.notifyDataSetChanged();

                try {
                    MakeConnection2(RvAdapter, query);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                // mSearchView.close(false);
            }
        });
        mSearchView.setAdapter(searchAdapter);

**Comment by lapism** [comment]
Nothing? Weird. And sample app is working fine. Maybe it will be RTL problem in adapter. But I am so sorry, right now I do not have time to check where is that problem.
