### ISSUE TITLE
SetOnFocusChangeListener on the SearchEditText

### ISSUE THREAD

**Issue by iamtodor** [lapism/SearchView#136]
The recycler view with suggestions doesn't appear if I set focus listener to the edit text. Do we have some work around here?

**Comment by lapism** [comment]
Please check the code of the lib and you will find out that there are many callbacks with edittext.removeFocus. So it is not neccesary to set focusListener to SearchView.

**Comment by iamtodor** [comment]
Please, why you talk about remove focus? I do not want to remove focus. I have some views, which should get `Visibility.GONE`, while `SearchEditText` has focus and when focus disappears, they have to be visible. It's not about remove focus.

**Comment by lapism** [comment]
Oh. Ok, now I know what you mean.

**Comment by iamtodor** [comment]
Thank you :)

**Comment by lapism** [comment]
I am not really sure what needs to be changed. And I am so sorry, but right now I do not have for this project till August.

**Comment by lapism** [comment]
Time*
