### ISSUE TITLE
RevealOutAnimation - incorrect "cy"

### ISSUE THREAD

**Issue by ultraon** [lapism/SearchView#14]
Hello, thank you for your work, it's very powerful tool, and i like it :-)

And i have proposition to fix ```SearchAnimator.revealOutAnimation()```. In current source code i see ```int cy = view.getHeight() / 2```, and when i open SearchView with suggestions and try to close it, then SearchView is going to wrong way  (reveal out animation is finished on not to starting point (SearchIcon) but on half of Search layout height (SearchView height + RecyclerView height).

Could you please change ```SearchAnimator.revealOutAnimation()```:
```int cy = view.getHeight() / 2;```
with 
```int cy = 0;```

**Comment by lapism** [comment]
Hi, I just tried it and you are right about that. Quick fix + new Gradle will be tomorrow.

**Comment by ultraon** [comment]
Hello, thanks for fast resolving, but it seems it doesn't work properly. First time it works well, but next open/close search view doesn't work properly (as it was before fix). Actually my case: on open search view i show default suggestions (categories), when user types in search view i load new suggestions and set new adapter in search view. So after first showing search view real hight is bigger then initialized height. So need to reopen this issue, i think.

**Comment by lapism** [comment]
You are welcome. If I understand to your case good then animation (after last fix) does not count real height of view. It is not a new bug, It has been changed like that for reason that reveal animation should be same for in and out state. It works now with 48dp height of view every time.
BUT:
That means it doesn't work with suggestions and recyclerview items. It will be fixed after I will have more time for this project.

**Comment by ultraon** [comment]
Hello, what about another solution. You can pass to SearchAnimator 2 views, one for apply animation, another for calculating start/finish animation points. In this case we can pass CardView & EditText to SearchAnimator methods.
Of course there is another true way for resolving this issue, make interface of animator and give a chance to clients of SearchView to set their own implementation.

**Comment by lapism** [comment]
I was thinking about first solution. But right now I don't have time for this project. You can fork it and change some parts, if you have some interesting ideas for improvements. After that just send me a pull request.

**Comment by ultraon** [comment]
Ok, i'll try

**Comment by ultraon** [comment]
Done with PR, see https://github.com/lapism/SearchView/pull/15

**Comment by lapism** [comment]
1.3.8 released :)
