### ISSUE TITLE
One Of The complex library i ever seen

### ISSUE THREAD

**Issue by younas-bangash** [lapism/SearchView#140]
Error:Execution failed for task ':sample:mergeDebugResources'.
> Error: java.io.FileNotFoundException: E:\AndroidStudio Projects\SearchView\sample\build\intermediates\res\merged\debug\drawable-xhdpi-v4\abc_btn_radio_to_on_mtrl_000.png (The requested operation cannot be performed on a file with a user-mapped section open)

**Comment by lapism** [comment]
It looks like a problem in support lib. In your project, please use last version of the support libraries and last version of my library.
