### ISSUE TITLE
Voice search problem

### ISSUE THREAD

**Issue by wjdtmddnr24** [lapism/SearchView#141]
Hello I am trying to use this library to use search view. 
I was trying to use voice search function.
When spell the words I want to search, it looks like the searchview recognizes the voice but it doesn't show the word it recognized.
I added Record_Audio permission on androidmanifest and i also added the requesting permission code for android 6.0+ but it still didnt work. 
I also tried on android 5.0 but it has the same problem.
I added onQueryTextListener for the searchview.
Am I missing some part which is necessary to use the voice search function or is it a bug?

**Comment by lapism** [comment]
Maybe it can be a bug , but I am not able to try it or fix it in next 14 days. Please wait. Thank you.

**Comment by lucasfernog** [comment]
The onActivityResult callback is necessary (check sample app)
