### ISSUE TITLE
Problems with showing in the middle of the screen and voice input

### ISSUE THREAD

**Issue by Komatoz** [lapism/SearchView#142]
Hi! 
Very useful lib, thank you for it! 

I have 2 problems (tested in Samsung Galaxy Note 4, Android 6). 

1)  I'm trying to put a SearchView in the  middle of the screen by vertical (in fragment). But the view doesn't have the  bottom border. How to fix that? 
![1](https://cloud.githubusercontent.com/assets/6008311/17412793/3b0abe50-5a87-11e6-91ab-49e0b878c5c8.png)

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
                xmlns:app="http://schemas.android.com/apk/res-auto"
                xmlns:tools="http://schemas.android.com/tools"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical" >
    <com.lapism.searchview.SearchView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_centerVertical="true"
        android:paddingBottom="100dp"
        app:search_divider="true"
        app:search_shadow_color="true"
        app:search_version="toolbar_icon"
        app:search_voice="true"
        app:search_voice_text="Говорите"
        />
</RelativeLayout>`

2) When I touch the SearchView and the keyboard shows, I try to use the Voice Input and touch it's icon. But  the Voice Input doesn't appear and the keyboard disappears. I think it's incorrect work - in this case Voice Input must go. 

![2](https://cloud.githubusercontent.com/assets/6008311/17413098/8c6f3c70-5a88-11e6-9c88-9d2d390a7c89.png)

Thank you!

**Comment by lapism** [comment]
1) give  BottomMargin to SearchView or put another component there. It is behavior of CardView.
2) I will check it ASAP.

**Comment by Komatoz** [comment]
1) BottomMargin  didn't help. What do you mean - another component? What component?

2) Thank you I'll wait.

**Comment by lapism** [comment]
This happens when you have small space under SearchView. Try to to put CardView on the same place and you will see the same behavior. Component = I meant for example Button.
