### ISSUE TITLE
[Enhancement] Options to close search view when close keyboard

### ISSUE THREAD

**Issue by joxad** [lapism/SearchView#143]
Hi,

Firstly, thanks for your lib, it is very usefull and easy to integrate.

I would have a request for you. For now I use this view as a menu item, and I go to a fragment search to do my research while showing the searchview . I works well but when I want to hide the keyboard to see all result, the search view close because it goes into this :

SearchEditText.java

```java
 @Override
    public boolean onKeyPreIme(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_UP) {
            if (mSearchView != null && mSearchView.isSearchOpen()) {
                mSearchView.close(true);
                return true;
            }
        }
        // return super.onKeyPreIme(keyCode, event);
        return super.dispatchKeyEvent(event);
    }

```

I was thinking of adding a new attribute to the material searchview, 

        <com.lapism.searchview.SearchView
            android:id="@+id/search_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:search_divider="true"
            app:hide_on_keyboard_close="true" />

In this case in SearchEditText : 

```java
 @Override
    public boolean onKeyPreIme(int keyCode, KeyEvent event) {
       if( mSearchView.shouldHideOnKeyboardClose())  {
        if (keyCode == KeyEvent.KEYCODE_BACK && event.getAction() == KeyEvent.ACTION_UP) {
            if (mSearchView != null && mSearchView.isSearchOpen()) {
                mSearchView.close(true);
                return true;
            }
        }
       }
        // return super.onKeyPreIme(keyCode, event);
        return super.dispatchKeyEvent(event);
    }

```

I 'll do a PR for all that

**Comment by lapism** [comment]
THANK YOU FOR IT.  I will add it this week. Or next one. After I will be done with every issue and pull request I will release new version ASAP.

**Comment by joxad** [comment]
@lapism Thanks :) tell me when you update the lib version on gradle ! 
By the way I use you project on my app https://github.com/joxad/zikobot , which is on beta on google play for now https://play.google.com/apps/testing/com.startogamu.zikobot

**Comment by lapism** [comment]
Of course. I am working on it :).
