### ISSUE TITLE
History suggestions

### ISSUE THREAD

**Issue by Komatoz** [lapism/SearchView#150]
Hi.

2 questions about History suggestions.

1. How to force to show history suggestions after focusing the Search View? Now they appears only after typing the first letter.

2. I want to use the  Search Views in 2 different parts of my app for searching different things. Is it possible to have separate independent history databases for them? How?

**Comment by lucasfernog** [comment]
1- that behavior is already working, check sample app or send me your code

2- you are going to need to implement that (i was thinking about pull request it, but idk)

**Comment by Komatoz** [comment]
1. I just got it. i used 

  SearchAdapter searchAdapter = new SearchAdapter(this);

instead of 

 List<SearchItem> suggestionsList = new ArrayList<>();
  SearchAdapter searchAdapter = new SearchAdapter(this, suggestionsList);

Now it works properly.

2. Thank you, it would be nice to implement that in your great lib!

**Comment by lucasfernog** [comment]
Actually it's not mine, but i'll do it maybe tomorrow because i need it too.

The first constructor of searchAdapter should work... weird.
