### ISSUE TITLE
Focusing the Search View with open keyboard

### ISSUE THREAD

**Issue by Komatoz** [lapism/SearchView#151]
Hi once again!

I want to see the Search View in focus and with open keyboard after opening the Activity. 

But when I make   searchView.addFocus(); searchView.showKeyboard();  keyboard doesn't appear. 

What i make wrong?

**Comment by lucasfernog** [comment]
try using the open() function (the boolean parameter doesn't matter with version_toolbar)

**Comment by Komatoz** [comment]
Thank you, that works!
