### ISSUE TITLE
When Fragment rotates, keyboard hides

### ISSUE THREAD

**Issue by DenisMondon** [lapism/SearchView#155]
Hi!

I'm using SearchView inside my Fragment.
When I **open(true)** my SearchView, the keyboard is showing.
When I **rotate my phone**, the SearchView is still shown but the keyboard has gone.

Even using searchView.onSaveInstanceState() and searchView.onRestoreInstanceState(...).
(When restoring the view, searchView.isSearchOpen() is false).

Here is my code:

saving:
```java
outState.putParcelable(EXTRA_KEY_SEARCH_VIEW, searchView.onSaveInstanceState());
```

restoring:
```java
Parcelable parcelable = savedInstanceState.getParcelable(EXTRA_KEY_SEARCH_VIEW);
searchView.onRestoreInstanceState(parcelable);
if (searchView.isSearchOpen()) {
    searchView.showKeyboard();// not called
}
```

Thanks!

Denis

**Comment by lapism** [comment]
I will check it ASAP.

**Comment by DenisMondon** [comment]
Hi!

I'm using right now the 3.5 version but the keyboard still hides when rotating the screen.

**Comment by lapism** [comment]
it will be fixed in next version. I hope. I working on it.

**Comment by DenisMondon** [comment]
Ok thx :D
