### ISSUE TITLE
How add custom searchitem?

### ISSUE THREAD

**Issue by nikhilkilivayil** [lapism/SearchView#16]
I need to add two textview in a row. Can I add this?

**Comment by lapism** [comment]
No, because you can't  change recyclerview adapter and xml layout of item. but you can copy the project and do some custom changes ;)

**Comment by nikhilkilivayil** [comment]
OK. I will make changes. Thanks

**Comment by lapism** [comment]
If will do some interesting changes and library will be still 
usable then send me a pull request. I will pull it to the master.

**Comment by nikhilkilivayil** [comment]
Ok. let me try :)
