### ISSUE TITLE
SearchView auto resize after running from background.

### ISSUE THREAD

**Issue by ThuyKhanh** [lapism/SearchView#163]
I run the  example. When the first time app launch, Searchview is displayed with margin-top, margin-bottom, margin-left, margin-right. When the app comes back from the background, Searchview is displayed with no margin.
Detail image of issue at: https://plus.google.com/115027304727901283630/posts/fogvz7WUq2g

p/s: I got the same problem when I added Searchview to my project.

**Comment by lapism** [comment]
use method setMargin in onPostCreate. Or set your custom margin in xml.

**Comment by ThuyKhanh** [comment]
Plz check out this video: https://www.youtube.com/watch?v=w9WNt7t3jU0
At same option: "Light Toolbar". SearchView has the different margin ( top, bottom, left, right). 
At the first time when the same app launch, SearchView is displayed without margin, when to select " Tool Toolbar" from navigation drawer SearchView is displayed with margin.
Plz check.

**Comment by lapism** [comment]
I know, I know. I gave you answer how to change that in your project. In sample I will have to fix it.
