### ISSUE TITLE
lollipop and kitkat menu item searchview

### ISSUE THREAD

**Issue by 0wzZZzz6** [lapism/SearchView#167]
Why is that in kitkat the searchview is good and in lollipop no searchview appears when tapping search icon.

![screenshot_1](https://cloud.githubusercontent.com/assets/11011672/18246429/37c96504-739e-11e6-84d5-2561e3dc4045.png)

**Comment by lapism** [comment]
Hmm. I do not know but. I will try it.

**Comment by lapism** [comment]
I was trying it a few minutes ago on Lenovo tablet with Lollipop and everything works. So try it on real device and let me know.

**Comment by 0wzZZzz6** [comment]
I used relative layout as the parent view of coordinator layout and its working now. 
thanks.
