### ISSUE TITLE
How to use this library with umano/AndroidSlidingUpPanel

### ISSUE THREAD

**Issue by cuong0993** [lapism/SearchView#168]
Hi all,
I need to use this library with AndroidSlidingUpPanel by umano.
My activity layout:
`
<android.support.v4.widget.DrawerLayout
    android:id="@+id/drawer_layout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <com.sothree.slidinguppanel.SlidingUpPanelLayout
        xmlns:sothree="http://schemas.android.com/apk/res-auto"
        android:id="@+id/sliding_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:gravity="bottom"
        sothree:umanoPanelHeight="64dp"
        sothree:umanoShadowHeight="4dp"
        sothree:umanoParallaxOffset="100dp"
        sothree:umanoDragView="@+id/dragView"
        sothree:umanoOverlay="false"
        sothree:umanoScrollableView="@+id/main">

        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="?attr/colorPrimary"
                app:layout_scrollFlags="scroll|enterAlways"
                android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"/>

            <FrameLayout
                android:id="@+id/main_fragment"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                layout="@layout/fragment_library"
                android:layout_below="@id/toolbar"/>

        </RelativeLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="#ffffff"
            android:orientation="vertical"
            android:clickable="true"
            android:focusable="false"
            android:id="@+id/dragView">

            <fragment
                .../>

            <fragment
                ..."/>
        </LinearLayout>

    </com.sothree.slidinguppanel.SlidingUpPanelLayout>

    <com.lapism.searchview.SearchView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <include layout="@layout/include_drawer_list"/>

</android.support.v4.widget.DrawerLayout>`
When i use mSearchView.open(true, item); search view opens immediately no matter which value of animation duration i set.
Please help!

**Comment by lapism** [comment]
I will try it ASAP, but it can be some problem of compatibility between those two libraries.
