### ISSUE TITLE
Search custom cursor

### ISSUE THREAD

**Issue by brunomassa** [lapism/SearchView#170]
could you add the possible of change the cursor, I want to put other cursor in my app.

Thanks

**Comment by lapism** [comment]
What do mean exactly?

**Comment by brunomassa** [comment]
the same thing that an edittext.

a thing like that:

Create a custom cursor xml like this for exemple:

`<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android" >
    <size android:width="1dp" />
    <solid android:color="@color/colorAccent"  />
</shape>`

and put in edittext using this:

`android:textCursorDrawable="@drawable/yourcustomcursor.xml"`

I want a thing like that.

**Comment by lapism** [comment]
Ok, I will add it to next version.

**Comment by brunomassa** [comment]
thanks

**Comment by lapism** [comment]
It will be added in 3.6.2, but I am not sure if it will work because I used a reflection.
