### ISSUE TITLE
Realm support

### ISSUE THREAD

**Issue by debjitk** [lapism/SearchView#173]
I am trying to build a RealmSearchAdapter for SearchView. I would suggest along with providing a SearchAdapter you should also implement a SearchAdapter interface so that it can be implemented based on certain requirements.

**Comment by lapism** [comment]
I am open to every pull request :).

**Comment by debjitk** [comment]
Sure

**Comment by RJFares** [comment]
Did you add one yet? I was thinking about doing the same thing

**Comment by lapism** [comment]
You can write your own adapter and set it with .setAdapter method.

**Comment by RJFares** [comment]
Thanks :) just asking if @debjitk already wrote one abstract enough to be shared with realm community.

**Comment by lapism** [comment]
OK. If you need something in library, just send me a pull request. Right now I do not have much time for this library...
