### ISSUE TITLE
How do you update Suggestions List?

### ISSUE THREAD

**Issue by TinasheMzondiwa** [lapism/SearchView#175]
In onQueryTextChange how can I update my suggestions list?
I keep getting 'RecyclerView does not support scrolling to an absolute position. Use scrollToPosition instead'

**Comment by lapism** [comment]
https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchAdapter.java

Use setSuggestionList.

**Comment by TinasheMzondiwa** [comment]
Thank you..
