### ISSUE TITLE
how to set the searchview hide in a default activity?

### ISSUE THREAD

**Issue by HelloLollipop** [lapism/SearchView#179]
just like the light menu item activity

**Comment by lapism** [comment]
use menu item and .animate(false). Also you can use setNavigationIconArrowHamburger().

**Comment by karanrazdan** [comment]
I'm using a menu item but where exactly do I use .animate(false) and setNavigationIconArrowHamburger().

**Comment by lapism** [comment]
where you want, but after findViewById
