### ISSUE TITLE
How to achieve hamburger-to-arrow animation when menu item search opens?

### ISSUE THREAD

**Issue by kevcgrant** [lapism/SearchView#181]
In the sample app, when the menu item search opens, the the arrow in the search view animates from a hamburger icon.
I'm not seeing this in my app, it just displays the arrow (using 3.7).

How is this achieved?

**Comment by lapism** [comment]
Hi, since version 3.6 the Searchview has method SearchView.setNavigationIconArrowHamburger(). It gives you animated arrow.

**Comment by kevcgrant** [comment]
Not sure how I missed that one, thanks!

**Comment by csbenz** [comment]
Note:
SearchView.setNavigationIconArrowHamburger() was deprecated in 4.0 and I think we should now use SearchView.setArrowOnly().
