### ISSUE TITLE
SearchView can't detect begin opened after removeFocus / clearFocus

### ISSUE THREAD

**Issue by Shnizlon** [lapism/SearchView#183]
I'm using this SearchView in my app in multiple fragments, in one of the fragments I use SearchView to filter a list while typing (onQueryTextChange), and I ran into two problems. First, I can't figure out how to avoid closing of SearchView when touching outside the view, is there an option only to hide keyboard and not close SearchView completely? (Like WhatsApp SearchView behaviour). Second problem is I use clearFocus to hide keyboard on onQueryTextSubmit, unlike AppCompat SearchView, after using it, SearchView can't detect anymore being opened, which cause a issue that onBackSearch close the fragment while SearchView is still opened. 

I made a video showing both AppCompat SearchView behaviour and your SearchView behaviour, hopefully it will help you to understand my issue: goo.gl/pM3mEF

**Comment by lapism** [comment]
Hi, I will try to fix it ASAP. I hope in next release.

**Comment by Shnizlon** [comment]
Thanks! Highly appreciate it!

**Comment by lapism** [comment]
And btw. you can use method setShadow(false) for issue 1.

**Comment by Shnizlon** [comment]
Wonderful, it worked, thanks!

**Comment by lapism** [comment]
For issue 2 I am not really sure how and what I should change. Maybe you can take a look on a project code and do some necessary changes by yourself. I am open to every pull request.

**Comment by lapism** [comment]
In the meantime I am going to release version 3.8 with last pull requests and method setHeight.

**Comment by Shnizlon** [comment]
Ok, thank you for your help, I'll dig into library source later this week and will try to fix it.
As a workaround for now instead of calling clearFocus on onQueryTextSubmit I call hideKeybord.
Did you see my question about hiding suggestions? (Edited my previous comment).

**Comment by lapism** [comment]
Sure. I do not have much time right now sorry. Yeah, I have seen it but it looks like problem in your app, not in library. 

What do you mean exactly? Just do not use them if you do not want them :D

**Comment by Shnizlon** [comment]
I have two fragments under same activity. I want to show suggestions only in one of the, so what I did is to create a return SearchView method in MainActivity with a boolean: http://pastebin.com/raw/h8RHe1iB

And I call it from fragment onCreateView:
        mSearchView = ((MainActivity)getActivity()).getSearchView(true, true);

**Comment by lapism** [comment]
Any news with your issue?
