### ISSUE TITLE
Search History

### ISSUE THREAD

**Issue by Shakezulla57** [lapism/SearchView#186]
I must be missing something but I can't get the history to show up. Here's how I'm initializing my adapter.

`SearchAdapter searchAdapter = new SearchAdapter(this);`
`searchAdapter.setDatabaseKey(1);`
`searchView.setAdapter(searchAdapter);`

What else do I need to do? It doesn't look like the sample does anything more than that. Any guidance is appreciated.

**Comment by lapism** [comment]
You should carefully read the sample. And use database from the library.

**Comment by lucasfernog** [comment]
BaseActivity#getData(String, int) is important (mHistoryDatabase.addItem(new SearchItem(text));).

**Comment by lapism** [comment]
... exactly :)
