### ISSUE TITLE
Failed to resolve: com.lapism:searchview:3.8.1

### ISSUE THREAD

**Issue by andkishor** [lapism/SearchView#193]
compileSdkVersion 23
    buildToolsVersion "22.0.1"
    useLibrary 'org.apache.http.legacy'

    defaultConfig {
        applicationId '----------'
        minSdkVersion 21
        targetSdkVersion 23
        versionCode 21
        versionName '2.0'
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

and this are my gradle files versions

   compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'

i want to use your library but i don't want to change my gradle file structure as its dependent 
but i am getting "Failed to resolve: com.lapism:searchview:3.8.1" this error.
Can you please help me.

**Comment by lapism** [comment]
please check version history in Readme and use version which you want.

**Comment by lapism** [comment]
last is 4.0 with appcompat v25.0.0

**Comment by andkishor** [comment]
I found compile 'com.lapism:searchview:2.1.1' this version as my requirement but still getting error
"Error:(168, 13) Failed to resolve: com.lapism:searchview:2.1.1"

**Comment by lapism** [comment]
OMG. It has been deleted because this version had bugs. Again, please check VERSION HISTORY in Readme and use version which you want.
