### ISSUE TITLE
i hava change SDK to 24 , why still call me Error:Failed to resolve: com.android.support:design:25.0.0 

### ISSUE THREAD

**Issue by Werb** [lapism/SearchView#194]
i want to use SDK 24 and i change it :

 compileSdkVersion 24
 buildToolsVersion "24.0.3"
 compile 'com.android.support:appcompat-v7:24.2.1'
 compile 'com.android.support:recyclerview-v7:24.2.1'
 compile 'com.android.support:cardview-v7:24.2.1'
 compile 'com.android.support:design:24.2.1'

but when i gradle sync

it still call me Error:Failed to resolve: com.android.support:design:25.0.0 

thx u  please ~

**Comment by lapism** [comment]
I do not know....library is based on last version of support libraries, so you should probably use same version in your project.
