### ISSUE TITLE
Crash on Android 5.0!

### ISSUE THREAD

**Issue by by-syk** [lapism/SearchView#195]
Today, I find that my app with SearchView library crashed on Android 5.0 (API 21). (It works OK before Android 5.0 and above Android 5.0.) And I don't understand the LogCat message, it likes:
```
A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: can't call void android.view.View.setElevation(float) on null object
A/art: art/runtime/check_jni.cc:65]     in call to CallVoidMethodV
A/art: art/runtime/check_jni.cc:65]     from void android.animation.PropertyValuesHolder.nCallFloatMethod(java.lang.Object, long, float)
A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
...
```

What's more, I installed the latest **SearchView Sample** app on a Android 5.0 device, it crashed, too. So I think it's a BUG of **SearchView**.

**Comment by lapism** [comment]
So this bug happens only on API 21 ( Android 5.0 ) ?

**Comment by by-syk** [comment]
Yes, only API 21. So is your sample app.

**Comment by GustavoHGS** [comment]
Hay lapism, have you already fixed this bug? For API 21?

**Comment by J-Yen** [comment]
I have the same problem, only on Android 5.0.

**Comment by lapism** [comment]
no, because I do not have time...you can check it by yourself and send me a pull request.

**Comment by J-Yen** [comment]
Unfortunately I do not have enough experience to fix the problem. I'm building my first Android app for a school project so please if anyone else can take a look at this problem i will be very gratefull.

**Comment by Vovaxo** [comment]
I've found a workaround. 
To fix this problem you have to update your XML file which contains SearchView and AppBarLayout. Add android:stateListAnimator="@null" to your AppBarLayout as shown below.

```
 <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        **android:stateListAnimator="@null"**
        android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">
```
It will shows you warning that android:stateListAnimator="@null" Attribute stateListAnimator is only used in API level 21. But I've checked source code of the library and it crashes in the SearchBehavior class when it tries to set mAppBarLayout.setStateListAnimator(null);

**Comment by Vovaxo** [comment]
Also if change in `SearchBehavior` class  mAppBarLayout.setStateListAnimator(null); it will fix the problem.

**Comment by J-Yen** [comment]
Many thanks!!! It works.

**Comment by Vovaxo** [comment]
@J-Yen You're welcome. Also I've added an answer to your [question](http://stackoverflow.com/questions/40928788/cant-call-void-android-view-view-setelevationfloat-on-null-object/40941206#40941206) on StackOverflow. I would appreciate if you accept my answer.

**Comment by RJFares** [comment]
+1

**Comment by lapism** [comment]
I will add it ASAP

**Comment by vkhodonovych** [comment]
@lapism Why have you reopened this issue? Is there any drawback of this?

**Comment by lapism** [comment]
Because I will need to read it when I will have more time for this project.
