### ISSUE TITLE
Update History/Suggestion list (java.lang.IllegalArgumentException)

### ISSUE THREAD

**Issue by guibirk** [lapism/SearchView#197]
What is the proper way to update the History/Suggestion list? Every time that I try to recreate the adapter and set it again on the search view, or try to modify the suggestionsList and call notifyDataSetChanged() on the existing adapter, I get the "java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true"

Basically, the steps to reproduce this exception are:
1 - Set the adapter;
2 - Open the search box;
3 - Close the search box;
4 - Try to update the adapter (setting a new adapter or calling notifyDataSetChanged)

I need to refresh the suggestions list based on a REST service that keeps updating the suggestions based on multiple services. Based on the current screen, I need to update the suggestions list.

**Comment by lucasfernog** [comment]
Try the SearchAdapter#setData method.

**Comment by guibirk** [comment]
@lucasfernog that's it! Thank you.
