### ISSUE TITLE
On actionbar back press 

### ISSUE THREAD

**Issue by nilabja1312** [lapism/SearchView#20]
Whenever I press the actionbar back button the search opens and then closes and then the back operation is executed

**Comment by lapism** [comment]
It is working exactly like Play Store section My apps. So should check your code. And completely rewritten new version is coming soon.

**Comment by nilabja1312** [comment]
okay, will be waiting for the new version, and will try to upload a video depicting my issue,

**Comment by lapism** [comment]
OK, I think error is somewhere in your code. Check sample application in the project and you will see. But deffinetely I going to take a look on your problem.

**Comment by lapism** [comment]
A please check this > https://github.com/lapism/SearchView/issues/13. Maybe it helps.

**Comment by nilabja1312** [comment]
please take a look
"https://drive.google.com/file/d/0ByaJrf_uCJhDSGdNM2gwdGx6dkU/view?usp=sharing"

**Comment by lapism** [comment]
I see. So, try this. It must be somewhere in your code.

    @Override
    public void onBackPressed() {
        if (mSearchView != null && mSearchView.isSearchOpen()) {
            mSearchView.closeSearch(true);
        } else if (mDrawerLayout.isDrawerOpen(GravityCompat.START)) {
            mDrawerLayout.closeDrawer(GravityCompat.START);
        } else {
            if (mBackPressed + TIME_INTERVAL > System.currentTimeMillis()) {
                super.onBackPressed();
            } else {
                final View coordinatorLayoutView = findViewById(R.id.coordinatorLayout);
                Snackbar.make(coordinatorLayoutView, R.string.exit, Snackbar.LENGTH_LONG)
                        .setAction("Exit", null)
                        .show();
            }
            mBackPressed = System.currentTimeMillis();
        }
    }

**Comment by lapism** [comment]
And again check carefully sample application. Also you have to set back operation to your Toolbar if you are using it.
