### ISSUE TITLE
Feature Req: advanced filtering

### ISSUE THREAD

**Issue by RJFares** [lapism/SearchView#200]
The way this lib gets search results is by converting strings to lower case and doing a string .contains(query).
In my app I use permutations so that "red apples" and "apples, red" would give the same search results.
I did this by extending SearchAdapter. But by doing this I lost history because mDatabaseKey is private.

Can you please either make it public/protected, or instead of 
```
if (string.contains(key)) {
 results.add(item);
}
```
put the condition in a public method such as compare(key,string), which the user can then override easily. (or both methods if you can)

I know you're busy but this is an easy feature :)

**Comment by lapism** [comment]
Sure. I will change it in next version on which I am already working.

**Comment by csbenz** [comment]
+1

**Comment by lapism** [comment]
mDatabaseKey will be public in 4.1.
