### ISSUE TITLE
RecyclerView does not support scrolling to an absolute position. Use scrollToPosition instead

### ISSUE THREAD

**Issue by J-Yen** [lapism/SearchView#203]
Every time the suggestion/history list change from number of items i get the following warning:

> W/RecyclerView: RecyclerView does not support scrolling to an absolute position. Use scrollToPosition instead

So every time the suggestion list change at user input i get a whole list of the same warnings. Does anyone know the cause?

Thx

**Comment by iainheng** [comment]
I am having the same problem. Does anyone knows how to fix it?

**Comment by lapism** [comment]
It is gonna be fixed in next release.I hope.

**Comment by beraybentesen** [comment]
When will you release next release ?

**Comment by lapism** [comment]
Since I got a new work as Android Developer I do not have much time for this lib. But I hope next week I will release it.

**Comment by apMadden** [comment]
Any update or work around?
