### ISSUE TITLE
Please restore 2.2 - Nothing works properly

### ISSUE THREAD

**Issue by behelit** [lapism/SearchView#210]
Can you please restore version 2.2 to the gradle dependency downloads. It's the only version that behaves correctly for me, none of the newer versions react to input, actions, back button, or keyboard actions correctly.

**Comment by lapism** [comment]
Hi, no. If you do not know how to use this library then do not use it. I have done sample project for reason ...

**Comment by behelit** [comment]
I think you misunderstood. The latest version of your library does NOT behave correctl in a fragment of a tablayout. The back button does NOT respond. The search action in keyboard, x icon in search bar, back button on phone, back iconm tapping outside of the serach view, ALL do not behave in the correct way where as they work perfectly in version 2.2.
I have downloaded the 2.2 source code and integrated it into my project instead, to avoid the bugs.
Thanks

**Comment by ratanoff** [comment]
@behelit Do you use SearchView exactly inside Fragnent, or in Toolbar?
In my app I use TabLayout with 3 fragments, and SearchView in Toolbar, and EVERYTHING you told about works perfectly with latest lib version!
