### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lapism** [lapism/SearchView#213]
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.Cursorandroid.database.sqlite.SQLiteDatabase.rawQuery(java.lang.String, java.lang.String[])' on a null object reference
com.lapism.searchview.SearchHistoryTable.getAllItems (SearchHistoryTable.java:116)
com.lapism.searchview.SearchAdapter$1.publishResults (SearchAdapter.java:111)
android.widget.Filter$ResultsHandler.handleMessage (Filter.java:282)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:150)
android.app.ActivityThread.main (ActivityThread.java:5643)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:799)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:689)

**Comment by PhilippeBoisney** [comment]
Same crash than you..
![image](https://cloud.githubusercontent.com/assets/6847959/23126640/0b8d6f22-f778-11e6-979b-2402123eca60.png)

**Comment by lapism** [comment]
ASAP :)

**Comment by lapism** [comment]
It should will be fixed in 5.0
