### ISSUE TITLE
back button not closing searchview

### ISSUE THREAD

**Issue by RezaOruji** [lapism/SearchView#217]
when i click on searchview it expands , then pressing back button does not close the searchview.
is there any way to close searchview with back button ?

**Comment by ratanoff** [comment]
Override activity/fragment onBackPressed method. SearcnView.close();

**Comment by ratanoff** [comment]
if (searchview.isOpen()) {
    searchview.close();
} else {
    super.onBackPressed();
}

**Comment by lapism** [comment]
Could you send me a log with this leak?

**Comment by RezaOruji** [comment]
i am testig it on Nexus 5 with android 6.0.1 . it didn't happened again , i will let you now if it happens again
