### ISSUE TITLE
Hint/Text size

### ISSUE THREAD

**Issue by Mathbl** [lapism/SearchView#22]
I was looking at the [spec](https://www.google.com/design/spec/patterns/search.html#search-in-app-search), and it looks like the textSize in the searchView is bigger.

That would be really nice if we could customize the textSize, maybe in xml using something like `app:search_text_size="18sp"`.

**Comment by Mathbl** [comment]
See PR #25

**Comment by lapism** [comment]
Thanks. I will add it to Jcenter ASAP

**Comment by Mathbl** [comment]
Great! At this point, I'm not sure what you are working on on your local branch.

On my side, I'll add at least two new features:
1. Ability to show a loading inside the SearchView with ability to provide a custom layout for the loading view.
2. Show an empty view in RecyclerView when there is no result.

If you are interested in any of those two features, I will gladly send a PR so you can review and test it and see if you wish to merge it into your lib.

**Comment by lapism** [comment]
Actually. Again, why not. It will stay here in Master branch until I will have time for merging with my local version.

**Comment by lapism** [comment]
especially for you I have uploaded version 1.5.
