### ISSUE TITLE
Bug when adding a lot of filters

### ISSUE THREAD

**Issue by csbenz** [lapism/SearchView#222]
If you add enough filters and the list reaches the end of the screen, the next filters aren't displayed correctly.

**Comment by csbenz** [comment]
That's because the lib is using a simple horizontal LinearLayout. We should use something like FlowLayout.

**Comment by csbenz** [comment]
@lapism Can I add an external library to add a FlowLayout instead of LinearLayout?

**Comment by lapism** [comment]
Hi. It looks good. I will try to release new version next week.

**Comment by csbenz** [comment]
Any news on the update?

**Comment by lapism** [comment]
Since I got a new work as Android Developer I do not have much time for this lib. But I hope next week I will release it.

**Comment by Dahnark** [comment]
Please, can you update this awasome library?

**Comment by lapism** [comment]
Sure. This is gonna be fixed in next release...

**Comment by lapism** [comment]
Already fixed with FlexboxLayout.
