### ISSUE TITLE
Update examples please!

### ISSUE THREAD

**Issue by diceroll123** [lapism/SearchView#225]
Found this lib and saw that everything that's currently up, at least for what I needed (menu item), was entirely wrong.

I figured it out, but some might not be able to.

---

For anyone finding this: you need to set the XML attributes found in README, it's not specified anywhere else, and the current example will only give you the toolbar.

*this said, I like the library! 👍*

**Comment by AllanWang** [comment]
It isn't wrong, but there are a lot of hidden components (like version code) that needed a bit of digging up to find. I will try to send a pull request to update the readme
