### ISSUE TITLE
Problem with gradle

### ISSUE THREAD

**Issue by k4netmt** [lapism/SearchView#226]
I have problem when I download source and run. Can you help me, please: 
> Error:Unable to find method 'org.gradle.api.tasks.Sync.getInputs()Lorg/gradle/api/internal/TaskInputsInternal;'.
> Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> <a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
> <a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

> 

Thank you for answer

**Comment by AllanWang** [comment]
Has this been fixed for you yet?

**Comment by lapism** [comment]
It has been a problem with Gradle...not my fault :D
