### ISSUE TITLE
Searchview not Centered

### ISSUE THREAD

**Issue by Heromine** [lapism/SearchView#229]
![screenshot_20170115-191858](https://cloud.githubusercontent.com/assets/7427881/21988346/421a38a4-dc07-11e6-81bd-3afed5d5c5d9.png)
As you can see the searchview is not centered in the toolbar since there is a margin in the top, and no margin at the bottom of the toolbar.Could you fix also this please? It looks very annoying to me.

**Comment by csbenz** [comment]
Are you using toolbar? Are you sure you don't have and extra margin or padding at the top of your root view? The lib is working well for me.

**Comment by Heromine** [comment]
Yea i have no margin

**Comment by lapism** [comment]
You can set your own margin in xml layout. So It is not a problem from the library.

**Comment by lapism** [comment]
In 4.1 will be no margin at all ... only with method setMargin or like XML attributte
