### ISSUE TITLE
SearchItem - Implements parcelable

### ISSUE THREAD

**Issue by Mathbl** [lapism/SearchView#23]
I would like to be able to save my List<SearchItem> so that it persists across orientation changes. 

We would be able to do something like this :+1: 

    private List<SearchItem> searchResults;

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        outState.putParcelableArrayList("searchResults", searchResults);
    }

and get it back with

`searchResults = savedInstance.getParcelableArrayList("searchResults");`

**Comment by lapism** [comment]
Thanks. It will be in future release, but because I am doing diploma thesis, I do not have time for this now.

**Comment by Mathbl** [comment]
I could send a Pull Request if you want!

**Comment by lapism** [comment]
sure, why not :). I will add it to master, but I do not know when I will do next version on Jcenter, cause my version on my PC is currently in development :)

**Comment by Mathbl** [comment]
Alright. I will be using your library in an app i'm working on. I need Parcelable, so I will probably implement it and send a pull request.

I will use jitpack.io on my branch while you find the time to publish on jCenter!

**Comment by Mathbl** [comment]
See PR #24
