### ISSUE TITLE
SearchView out of toolbar in 4.0

### ISSUE THREAD

**Issue by victordigio** [lapism/SearchView#235]
I have updated from 2.2 to 4.0 (because 2.2 was not available anymore), and searchView is not properly adapted into toolbar:

![image](https://cloud.githubusercontent.com/assets/15648001/22371908/59a8049c-e49a-11e6-9129-7f575c6c0671.png)

This is my xml:

    <?xml version="1.0" encoding="utf-8"?>
    <android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
                                        xmlns:app="http://schemas.android.com/apk/res-auto"
                                        xmlns:tools="http://schemas.android.com/tools"
                                        android:id="@+id/drawerLayout"
                                        android:layout_width="match_parent"
                                        android:layout_height="match_parent"
                                        android:fitsSystemWindows="true"
    >

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/coordinator"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        android:orientation="vertical">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="?attr/colorPrimary"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="@color/colorPrimary"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light" >

            </android.support.v7.widget.Toolbar>

        </android.support.design.widget.AppBarLayout>

        <LinearLayout
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="match_parent">
            <FrameLayout
                android:id="@+id/container"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                android:scrollbars="vertical"
                />

            <View android:layout_width="match_parent"
                  android:layout_height="1dp"
                  android:background="@color/gray_separator"/>

            <com.aurelhubert.ahbottomnavigation.AHBottomNavigation
                android:id="@+id/bottom_navigation"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom" />

        </LinearLayout>

     <com.lapism.searchview.SearchView
        android:id="@+id/searchView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:search_version="menu_item"
        app:search_theme="light"
        app:search_divider="false"
        app:search_hint="@string/search_bar_title"
        app:search_voice="true"
        app:search_voice_text="@string/search_bar_voice"
        app:search_animation_duration="300"
        app:search_shadow_color="@color/search_shadow_layout"
        />

    </android.support.design.widget.CoordinatorLayout>

    

</android.support.v4.widget.DrawerLayout>

**Comment by lapism** [comment]
Do not use setMargin method and use your own in XML.

**Comment by lapism** [comment]
It will be fixed in 4.1.
