### ISSUE TITLE
isSearchOpen() result may be wrong while using MenuItem Version

### ISSUE THREAD

**Issue by smartjinyu** [lapism/SearchView#237]
While using MenuItem version, I think that isSearchOpen() should return true if the SearchView is expanded, no matter whether focus is on it or not.  However, if we remove focus from the SearchView, this method will return false even if it is still expanded. It seems that setting mIsSearchOpen variable in open() and close() method would be a better choice than setting it in addFocus() and removeFocus().
I‘m not sure if it is the original meaning of isSearchOpen(). If so, I will submit a PR for that.

**Comment by vkhodonovych** [comment]
I do agree with @smartjinyu I had the same issue

**Comment by lapism** [comment]
Yes, you are right. So I am waiting for PR :]

**Comment by lapism** [comment]
Version 4.1 with many updates will be in two weeks.

**Comment by smartjinyu** [comment]
@lapism looking forward to that

**Comment by lapism** [comment]
Me too :D

**Comment by lapism** [comment]
Should be fixed in repository now.
