### ISSUE TITLE
SearchDivider has been made public, but newer versions aren't up on Maven

### ISSUE THREAD

**Issue by Thunderbottom** [lapism/SearchView#238]
You've fixed the problem [here](https://github.com/lapism/SearchView/commit/4b0dbc158378957bb37b1a4ca4bda53d32361b6a#diff-bf2a878ec3593e6852a29d41ff57b7e0R13), but the library hasn't been updated on Maven repositories. Please update it soon!

**Comment by lapism** [comment]
ASAP, do not worry :)

**Comment by Thunderbottom** [comment]
Thanks! Been waiting to continue a couple of my projects since quite some time, haha

**Comment by Thunderbottom** [comment]
How long before 4.1 is out? I know I can build and use it myself but I'd like to wait for you to _officially_ release it

**Comment by lapism** [comment]
Hi...I still need time to check everything. I could release it immediately, but not without bug check.

**Comment by Thunderbottom** [comment]
Alright, thanks. I'll wait for a while longer then :)
