### ISSUE TITLE
mBackImageView onClickListener

### ISSUE THREAD

**Issue by vkhodonovych** [lapism/SearchView#241]
I want to remove **onClickListener** from  **mBackImageView** but there is no possibility to do this as all **onClickListener**s are set in the **initView** method  such as mBackImageView.setOnClickListener(this);
This situation happens when I want to show search icon instead of default back button.

Is it possible to add method similar to setNavigationIcon() but with a listener?

**Comment by lapism** [comment]
setNavigationIconListener(View.OnClickListener) will be in version 5.0 :]
