### ISSUE TITLE
SearchView open overlap

### ISSUE THREAD

**Issue by EpsilonOrionis** [lapism/SearchView#243]
Hi, I don't know if this is a problem related with my layout, but I also tried with your sample application and it occurs even there. When I open the SearchView I would like to overlap all the views behind it e.g. (FloatingActionButtons, Buttons and so on...), but the effect that I get is that all the views are attached to the keyboard and I would like to have them behind it. Is there a way to do so?

Thank you for your time :)

**Comment by lapism** [comment]
SearchView.setShadow(false) should help you...

**Comment by EpsilonOrionis** [comment]
No, it doesn't

**Comment by lapism** [comment]
So try set TRUE ... and check if your layout is correct like in example.

**Comment by EpsilonOrionis** [comment]
It's the adapter. This problem occurs when I set the adapter

**Comment by lapism** [comment]
Sorry but I do not have time right now for this project. But I am open to every pull request ...

**Comment by AllanWang** [comment]
Is this still an issue? If so care to post a screenshot?

**Comment by aniqbukhairy** [comment]
its overlaping.

![1](https://cloud.githubusercontent.com/assets/14970145/24949003/bf769e5c-1f9e-11e7-847b-a9ba66ca3541.jpg)
![2](https://cloud.githubusercontent.com/assets/14970145/24949004/bf78e41e-1f9e-11e7-92fa-2ae537729cab.jpg)
![3](https://cloud.githubusercontent.com/assets/14970145/24949005/bf7a9926-1f9e-11e7-84f6-8ae4721c8de0.jpg)

**Comment by aniqbukhairy** [comment]
its overlapping

![1 374x640](https://cloud.githubusercontent.com/assets/14970145/24949091/0919a234-1f9f-11e7-8202-e2f0617534aa.jpg)
![2 378x640](https://cloud.githubusercontent.com/assets/14970145/24949092/091bf30e-1f9f-11e7-96fd-46cf765f08ec.jpg)
![3 374x640](https://cloud.githubusercontent.com/assets/14970145/24949093/091c5e3e-1f9f-11e7-9a74-a3fd00279d57.jpg)

**Comment by lapism** [comment]
I know but you should copy dependency from jCenter...code here must be fixed

**Comment by aniqbukhairy** [comment]
I redownload zip file and try to debug and its have error.
![1 640x209](https://cloud.githubusercontent.com/assets/14970145/24991865/8b229fae-2050-11e7-9c22-8e965be6d980.jpg)

**Comment by lapism** [comment]
I am working on this project, so it can be...functional version is on jCenter.
