### ISSUE TITLE
Practices for Hiding Suggestion

### ISSUE THREAD

**Issue by AllanWang** [lapism/SearchView#250]
Currently, when a user starts typing, the recyclerview is hidden by setting its visibility to gone ([Source](https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchView.java#L946))

1. There is no animation this way, should we clear the adapter instead?
2. Once a new query is submitted, there is sometimes a blink of the old data before the new data is added and shown
3. I haven't tested this anywhere but my app, but the first adapter change doesn't show for me; there is something with the [data changes](https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchAdapter.java#L187), though it looks like it should work.

**Comment by lapism** [comment]
I am going to take a look on this for next version.
