### ISSUE TITLE
Generics for adapter list

### ISSUE THREAD

**Issue by AllanWang** [lapism/SearchView#251]
* The ViewHolder can only hold a drawable and string (which makes sense), but the adapter list should allow for more variables in case they are needed when an item is clicked.

For example, if I have a list of `Person` objects, I can display their name in the search results, but require their age & id when a person is selected.

This can be done now by saving a list externally and referencing it with indices, but should be doable with generics.

I will be working on this when I have time.

**Comment by AllanWang** [comment]
I've tried this a while back and it didn't work too well. It's too much work trying to create parcelables for generic items.

**Comment by boswelja** [comment]
Doesn't Android Studio auto-create parcelable objects though?

**Comment by AllanWang** [comment]
There are annotations that do, but apart from that, I can no longer integrate it with the database since it is set to only save a key and a value. If all that because customizable we're essentially rewriting those components ourselves. I'm still thinking of other ways to go about that since the data can usually be retrieved by a single key, be it an id or a url for the item.
