### ISSUE TITLE
Custom menu icons like voice

### ISSUE THREAD

**Issue by NathHorrigan** [lapism/SearchView#252]
Is it possible to add menu icons like the voice search to the SearchView??. Specifically a Chromecast Icon.

Thanks in advance

**Comment by lapism** [comment]
No. But it is interesting idea for next release :]

**Comment by NathHorrigan** [comment]
Cool. I hope you get around to implementing the feature. Closed?

**Comment by lapism** [comment]
Sure...I will close this issue after it will be implemented :]

**Comment by NathHorrigan** [comment]
Was this ever implemented?

**Comment by lapism** [comment]
No. But I am working on new version so probably I will add it.
