### ISSUE TITLE
Is it possible to layout SearchView like in Google Maps

### ISSUE THREAD

**Issue by onirtuen** [lapism/SearchView#258]
Hi, 

I mean that the map is behind and around the SearchView:
![image](https://cloud.githubusercontent.com/assets/15869727/25589267/a6501c6c-2eb4-11e7-850a-3c38d250901a.png)
If yes, how you do that? 

Thank you,

Kind regards, 
Greg

**Comment by lapism** [comment]
Sure, use FrameLayout :]

**Comment by onirtuen** [comment]
Ouch, it was really stupid question :) 
Thank you!
