### ISSUE TITLE
Getting  "android.view.InflateException: Binary XML file line #24: Error inflating class com.lapism.searchview.SearchView .... Caused by: java.lang.ClassCastException: android.support.constraint.ConstraintLayout cannot be cast to android.widget.LinearLayout"

### ISSUE THREAD

**Issue by GeorgiAngelov** [lapism/SearchView#259]
So I tried adding the library via "compile project(':searchview')" and I am getting the following error:

`android.view.InflateException: Binary XML file line #24: Error inflating class com.lapism.searchview.SearchView .... Caused by: java.lang.ClassCastException: android.support.constraint.ConstraintLayout cannot be cast to android.widget.LinearLayout`

I haven't changed anything on the library so I am not sure why I'm getting this error.

I am also having this issue in the search_view.xml file regarding the ConstrainedLayout which may be related to my error:

```
This view is not constrained, it only has designtime positions, so it will jump to (0,0) unless you add constraints less... (Ctrl+F1) 
The layout editor allows you to place widgets anywhere on the canvas, and it records the current position with designtime attributes (such as layout_editor_absoluteX.) These attributes are not applied at runtime, so if you push your layout on a device, the widgets may appear in a different location than shown in the editor. To fix this, make sure a widget has both horizontal and vertical constraints by dragging from the edge connections.
```

**Comment by lapism** [comment]
you should use version from jCenter or branch version5.
