### ISSUE TITLE
SearchView Sample in GooglePlay

### ISSUE THREAD

**Issue by ultraon** [lapism/SearchView#26]
Hello, i've installed application SearchView Sample (updated), but there is no launcher, i can't start sample application. Please check it.

**Comment by lapism** [comment]
I see :-O. I do not know how it happened. Thanks. I will fix it.

**Comment by lapism** [comment]
Give me a feedback please if it will work. Thanks.

**Comment by ultraon** [comment]
Yes, it works now.
