### ISSUE TITLE
The simplest way to integrate SearchView in existing project

### ISSUE THREAD

**Issue by onirtuen** [lapism/SearchView#260]
Hi,

First, thanks for sharing your work!

If I need only strings (i.e. my list item is single TextView) and I'm not that familiar with RecyclerView and the stuff. What would be the easiest way to integrate SearchView into my App?

Thank you in advance,

Kindest regards, 

Greg.

P.S. Too bad there is no forum or a discussion here. I don't want to create issue when asking questions like that.

**Comment by lapism** [comment]
You should check the sample project. Branch ,,Version5" should work.
