### ISSUE TITLE
Bug on Android Support Library 25.3.1

### ISSUE THREAD

**Issue by CMathgician** [lapism/SearchView#262]
Hi,
I am using SearchView wrapped by CoordinatorLayout like this image below
![687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6469676974616c7472656e64732d75706c6f6164732d70726f642f323031352f31302f476f6f676c652d506c61792d53746f72652d6865616465722e6a7067](https://cloud.githubusercontent.com/assets/6632239/25744073/15a28d92-31c2-11e7-8e79-7aabad12ae32.jpeg)

When I update Android Support Library to 25.3.1 from 25.2.0
Something wrong is happen.

When I scroll my page, the toolbar/appbar collapse normally but the SearchView disappear (maybe invisible).

**Comment by lapism** [comment]
Hi, are you using version from jCenter or local forked repository? Could you send me your layout? 
I am working on new version 5.0 and I hope it will be released next week. So I can fix it if there is somewhere something :).

**Comment by CMathgician** [comment]
I'm using from jCenter.
What's new on version 5.0?

`<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/store"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/rv_store"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clipToPadding="false"/>

    <include layout="@layout/toolbar" />

    <com.lapism.searchview.SearchView
        android:id="@+id/search_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:animateLayoutChanges="false"
        app:search_clear_on_close="true"
        app:search_hint="Google Play"
        app:search_navigation_icon="@drawable/ic_drawer"
        app:search_version="toolbar"
        app:search_voice="false" />
</android.support.design.widget.CoordinatorLayout>`

**Comment by lapism** [comment]
5.0 is not finished yet. But after it will be released I will add Changelog.

**Comment by lapism** [comment]
I will take a look on your layout this weekend.

**Comment by CMathgician** [comment]
Is it close? Can you tell me where is the problem?

**Comment by lapism** [comment]
Change your layout like in example. Probably problem is in your layout. Or you can try version from newer version from code in repository.

**Comment by CMathgician** [comment]
I'm using
compile 'com.lapism:searchview:4.0'
I didn't get your updated code. For example search_theme 'play store'

Can u update to 4.1 before 5.0 release?

**Comment by lapism** [comment]
Probably after this weekend I will release source fixed source code and new version on jCenter...so stay tuned :)

**Comment by CMathgician** [comment]
Ok. Can I help you?

**Comment by lapism** [comment]
With what? Probably no. Maybe first I will release some 5.0.0-alpha1 version ...

**Comment by CMathgician** [comment]
To implement & test the new version.

**Comment by lapism** [comment]
Maybe after release of 5.0.0-alpha1 :)

**Comment by lapism** [comment]
Maybe after release of 5.0.0-alpha1 :)

**Comment by CMathgician** [comment]
Ok no problem. I hope it will be release as soon as possible

**Comment by lapism** [comment]
me too :D

**Comment by lapism** [comment]
I hope there will be a new version 5.0.0-alpha1 after this weekend.

**Comment by CMathgician** [comment]
Ready for release?

**Comment by lapism** [comment]
I hope so...it still needs some work, but I am working on it now.

**Comment by shahimclt** [comment]
@lapism  awesome library by the way. I too am patiently waiting for the release.

**Comment by lapism** [comment]
me too...next week maybe because I am almost done ... so 5.0.0-alpha1 will be released
