### ISSUE TITLE
Can't change the Hamburger Icon

### ISSUE THREAD

**Issue by paulito415** [lapism/SearchView#266]
I followed the instructions on https://github.com/lapism/SearchView/issues/148 to set the version to toolbar_icon but Android Studio reported "String types not allowed (at 'search_version' with value 'toolbar_icon'). Also I'm not sure in the latest README that type is there either. My build.gradle has compile 'com.lapism:searchview:4.0' following your README - should I upgrade to a later version?

Thanks,
Paul

**Comment by paulito415** [comment]
Ha! Allow me to answer my own question here... Through the "magic" of method autocomplete in Android Studio (duh! I should have done that in the first place), I was able to find the setNavigationIcon method that allowed me to set my own Drawable (a magnifying glass). Curiously though, this method was not mentioned in the documentation (README.md or CHANGELOG.md) or under the sample project at https://github.com/lapism/SearchView/tree/master/sample/src/main/java/com/lapism/searchview/sample. Would be great for future adopters of SearchView if you can update the documentation.

Thanks,
Paul

**Comment by Derek-X-Wang** [comment]
or use `app:search_navigation_icon` in xml

**Comment by paulito415** [comment]
Thanks Derek!

I actually have a different problem now. For some reason, after I set the navigation icon to my own icon, when I click on the text field, it doesn't change the navigation icon to a "back" button anymore. Usually with the hamburger, the icon turns into a back button (with animation) that I can click to clear the search and hide the keyboard. But after I set the navigation icon to my Drawable this doesn't happen anymore. Has anyone else also encountered this?

**Comment by paulito415** [comment]
After stepping into the `SearchView` code it wasn't apparent to me that setNavigationIcon was the method I needed. It seems that in `addFocus` / `removeFocus` there is a call to `mSearchArrow.animate()` from one state to another (hamburger to arrow). But I couldn't find the place where we set the icons that corresponding to each of the states. I know that `mSearchArrow` is the `Drawable` that is set into `mBackImageView` and the drawing should all be left to the internals of `mSearchArrow` (instance of `SearchArrowDrawable`). But stepping into the code of `SearchArrowDrawable` which extends `DrawerArrowDrawable`, it seems the "arrow" and the "hamburger" are drawn using `Paint` and are not image / icons at all. I further realize that `setNavigationIcon(Drawable)` just replaces `mSearchArrow` with my own - which means no more animation. So, that means whatever I'm seeing is consistent with the call I've made. But that still leaves my original question unanswered. Scouring the issues page led to numerous references to `VERSION_TOOLBAR_ICON` or `"toolbar_icon"` circa 2016, but I find no traces of either in any of the code. Is there really no way to do what I'm asking for?

**Comment by lapism** [comment]
Hi, I am working already on new version with a lot of changes. But that thing what you were asking for is not possible with jCenter or repository code. Only thing I can do is to add state parameter to navigationIcon listener in new version ...

**Comment by paulito415** [comment]
Thanks for the update! I'm not sure what you mean by jcenter or repository code. I'll just assume you mean with the latest version of your code what I'm asking for is not possible. 

But I was thinking. Maybe i can extend SearchArrowDrawable and instead of drawing with Paint, maybe I can overlay / render an image or something. Then I can just subclass your SearchView to use my own Drawable. Does that sound like it could work?

**Comment by lapism** [comment]
I am not really sure right now with actual version of the library. But I will add icon state listener to next version.
