### ISSUE TITLE
Toolbar shadow disappears

### ISSUE THREAD

**Issue by AnderGoig** [lapism/SearchView#268]
I'm not sure why, but the shadow of the Toolbar widget doesn't show when using this widget.

**Comment by lapism** [comment]
It is because AppBar parent is set with elevation 0dp in CoordinatorLayoutBehavior from SearchView....I have not found the solution yet.

**Comment by AlekseiBazhenov** [comment]
@lapism The shadow doesn't show because it's hidden in SearchBehavior. 
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    mAppBarLayout.setElevation(0); // TODO NO SHADOWS APPBAR
}
I've commented out these strings and the shadow works perfect for MenuItemActivity. But toolbar disappears on ToolbarActivity and FiltersActivity.

**Comment by lapism** [comment]
I know why it is happening but I haven't found the way how to fix it.
