### ISSUE TITLE
1.6 is not on bintray

### ISSUE THREAD

**Issue by aat-antoine** [lapism/SearchView#27]
When i check your bintray view

https://bintray.com/lapism/maven/searchview/view

I can see only 1.5.

Is it normal ?

Thx

**Comment by lapism** [comment]
Hi, interesting, because in my account I see it. Try 1.5 until I will figure it out why it is happening.

**Comment by aat-antoine** [comment]
It works perfect with 1.5 but with 1.6 my gradle says it can't find this dependency

**Comment by aat-antoine** [comment]
Here is a screen
![screen](https://cloud.githubusercontent.com/assets/1374372/12953414/a3f5d6fe-d01a-11e5-9f8a-8d49f8918361.png)

**Comment by lapism** [comment]
I know why others do not see 1.6. It is not public and I do not why. Maybe because I have changed method for uploading.

**Comment by lapism** [comment]
So I deleted 1.6 version from Bintray and I will upload new version soon. With a few changes. I apologize for that.

**Comment by aat-antoine** [comment]
okay ! No problem

**Comment by lapism** [comment]
Version 2.0 is out.
