### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by coder3101** [lapism/SearchView#274]
I just noticed that the transparent background of the image views (like arrow/mic) in the search_view.xml are visible to user when clicked. That looks weird.

Even though background attribute is set to
 
``` android:background="?attr/selectableItemBackground" ```

The transparent part of the image shows up when it is clicked.
A better alternative would be to replace the background attribute with this :

``` android:background="?attr/selectableItemBackgroundBorderless" ```

This will not only make the images selectable but this will also give it a rippling effect when it is clicked..

(Rippling effect is the same effect you get when you click an icon on actionbar like search/share..etc)

Hope it gets merged in next release.

**Comment by lapism** [comment]
Sure, I will add it.
