### ISSUE TITLE
SearchView width margins not showing after 2 nd time opening the app

### ISSUE THREAD

**Issue by gautam2682** [lapism/SearchView#277]
SearchView width margins are perfect when first time installing the app but restrating it shows no width default margin like the picture below . I have use the same layout and java files please help me out of this weird problem.
![screenshot_1497797092](https://user-images.githubusercontent.com/16800520/27261580-9cb24688-5463-11e7-9cd8-d97d7931f8e0.png)

Solved this problem by removing this line of code from sample 

`mSearchView.setOnMenuClickListener(new SearchView.OnMenuClickListener() {
            @Override
            public void onMenuClick() {
                mDrawerLayout.openDrawer(GravityCompat.START); // finish();
            }
        });
        customSearchView();
`
THANK YOU;)

**Comment by lapism** [comment]
Set your own margins in xml ;)

**Comment by gautam2682** [comment]
Its not just about the margins but back button arrow also blocks after reopening the application .In my other app the same code is working fine , i think any update has broken it. ;)


here is xml file copied from your previous sample code:-
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:ads="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/drawerLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"

    >



        


        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar"
            android:background="@android:color/transparent"
            android:stateListAnimator="@null"
            android:id="@+id/myappbar"
            >


            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:minHeight="60dp"
                app:layout_scrollFlags="scroll|enterAlways|snap"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light"
                android:layout_height="60dp"
                />

            <android.support.design.widget.TabLayout
                android:id="@+id/tabs"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"

                />

        </android.support.design.widget.AppBarLayout>

        

        <android.support.v4.view.ViewPager
            android:id="@+id/viewPager"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
        <FrameLayout
            android:layout_width="match_parent"
            android:id="@+id/main_Frame"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            >

        </FrameLayout>



        <com.lapism.searchview.SearchView
            android:id="@+id/searchView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            />
        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_gravity="bottom|end"
            android:orientation="vertical"
            android:layout_height="wrap_content">

            <LinearLayout
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:gravity="end">

                <android.support.design.widget.FloatingActionButton
                    android:id="@+id/floatingActionButton"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom|end"
                    android:layout_margin="16dp"
                    app:borderWidth="0dp"
                    app:elevation="6dp"
                    android:scaleType="center"
                    app:fabSize="normal"

                    />
            </LinearLayout>

        </LinearLayout>



    <android.support.design.widget.NavigationView
        android:id="@+id/navigation_view"
        android:layout_height="match_parent"
        android:layout_width="wrap_content"
        android:layout_gravity="start"
      />

</android.support.v4.widget.DrawerLayout> `
