### ISSUE TITLE
Search animator visibility changes

### ISSUE THREAD

**Issue by AllanWang** [lapism/SearchView#279]
This isn't urgent, but for some of your exit animations, I feel like you're missing some listeners. For example in [fade out](https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchAnimator.java#L28), the view should be set to gone after the animation, otherwise it will be hidden during the fade and you wouldn't see it.

I've attached some of [my](https://github.com/AllanWang/KAU/blob/master/library/src/main/kotlin/ca/allanwang/kau/utils/AnimUtils.kt#L93) implementations (in Kotlin) in case you want to copy those over.

**Comment by lapism** [comment]
Thanks I am going to check it.
