### ISSUE TITLE
showSearch boolean

### ISSUE THREAD

**Issue by Heromine** [lapism/SearchView#28]
` Error:(202,28) error: method showSearch in class SearchView cannot be applied to given types;
required: boolean
found: no arguments
reason: actual and formal argument lists differ in length`

What is wrong?

**Comment by lapism** [comment]
showSearch(true/false) for animation :)

**Comment by Heromine** [comment]
is it normal?
![screenshot_2016-02-14-15-53-42](https://cloud.githubusercontent.com/assets/7427881/13034355/4daeed8c-d333-11e5-8ad4-2a0fac16df55.png)

**Comment by lapism** [comment]
Why I have sample app there? Use it and add parameters to your layout or set it in the code.

**Comment by Heromine** [comment]
I am using v1.5 with all settings needed withiut changes.

**Comment by lapism** [comment]
But I am using 1.5 in my app and it is OK, so I do not know. Or you can wait for release 2.0, it will be out in a few days. And it will be a huge update :).
![screenshot_20160214-202339](https://cloud.githubusercontent.com/assets/8614327/13035916/9c415ad0-d35a-11e5-9b45-c34bd1ac0e51.png)

**Comment by Heromine** [comment]
I'll do it

**Comment by lapism** [comment]
2.0 is already out

**Comment by Heromine** [comment]
Update the readme if something has changed please.

**Comment by lapism** [comment]
of course. it is changed in my local repository already. Check Play Store sample and you will see news :)
