### ISSUE TITLE
Can you upload sample project folder

### ISSUE THREAD

**Issue by ganny26** [lapism/SearchView#280]
Hi,

Could you please upload sample project which is listed on play store

**Comment by lapism** [comment]
No, in next version will be better README. Project from Play Store will be deleted.

**Comment by xiaobailong24** [comment]
@lapism Is NEW README coming soon?

**Comment by lapism** [comment]
Yes, i am working on a new version... I hope it will be out in next week.

**Comment by lapism** [comment]
Check the README...
