### ISSUE TITLE
How to replace the menu button by the back button?

### ISSUE THREAD

**Issue by EmmanuelMess** [lapism/SearchView#282]
Is there some way to replace the menu button by the back button after the search has been done?
![screenshot_1498527011](https://user-images.githubusercontent.com/10991116/27566988-3ff8534e-5abf-11e7-9ba4-61a90a37f2cb.png)

**Comment by lapism** [comment]
for now setArrowOnly(), but this behavior will be changed.

**Comment by EmmanuelMess** [comment]
If I may bother you once more, when I click on the 'back' arrow when it is replacing the hamburguer button, it doesn't do anything, further debugging suggests that [`mIsSearchArrowHamburgerState == SearchArrowDrawable.STATE_ARROW`](https://github.com/lapism/SearchView/blob/master/src/main/java/com/lapism/searchview/SearchView.java#L620) is false. Is there something I'm missing or is this a bug? (It may also be my emulator acting up, but it doesn't seem like it).

**Comment by lapism** [comment]
Maybe. I will take a look on it ASAP.

**Comment by monajafi** [comment]
Hi
There is no setArrowOnly method in latest version how we should hide hamburger icon in latest version

**Comment by AlexeyGorovoy** [comment]
Has anyone managed to do it without forking the library?

**Comment by younas-bangash** [comment]
In new version you can set the icon

` mSearchView.setNavigationIcon(R.drawable.ic_back);`

**Comment by EmmanuelMess** [comment]
Will try when the new version reaches stability.
