### ISSUE TITLE
Bad margin color/translucent

### ISSUE THREAD

**Issue by DesarrolladorAndroid** [lapism/SearchView#286]
Hello,

With Nexus One API 15 emulator I am getting this issue (black/translucent space between checkbox):

<img src="https://i.imgur.com/zplx6pl.png" alt="Mountain View" style="width:304px;">

Should be (like the other emulators)

<img src="https://i.imgur.com/aadolcG.png" alt="Mountain View" style="width:304px;">

**Comment by lapism** [comment]
SET MARGIN !

**Comment by DesarrolladorAndroid** [comment]
How? The problem is that the searchview has all white in all android version except in api 15, there has this translucent or black space. I didn't set any margin there.

**Comment by lapism** [comment]
Oh, sorry, I did not see that black line...so I will fix it asap in next version which will be probably after this weekend.

**Comment by lapism** [comment]
I hope there will be a new version 5.0.0-alpha1 after this weekend.

**Comment by lapism** [comment]
Is this still an issue?

**Comment by Dahnark** [comment]
Yes, it is fixed, but now the checkboxes are black instead of using accent color. In the other version this checkboxes are using accent color.

**Comment by lapism** [comment]
Checkboxes will be fixed in next version. It is already fixed in my branch.
