### ISSUE TITLE
How do I use the search view as a menu item?

### ISSUE THREAD

**Issue by jordaneckhardt** [lapism/SearchView#287]
I'm trying to use the search view in `SearchView.VERSION_MENU_ITEM` mode. I have a menu resource file with the search view as a menu item. I've set the menu item's `app:actionViewClass` to `com.lapism.searchview.SearchView`, but when I try to access the menu item's action view from my activity in `onCreateOptionsMenu()`, it's always null. In other words, `menu.findItem(R.id.menu_resource_file_name).getActionView()` returns null. 

Instead of setting the menu item's `app:actionViewClass` attribute, I've also tried setting its `app:actionLayout` attribute to a new layout resource whose contents are just the search view as defined as in the README, but the `MenuItem`'s action view is still null.

I'd really appreciate any advice. Thanks in advance!

**Comment by YESALAM** [comment]
Put the SearchView as the child of your activity main viewgroup and bind it in activity code .
Initialize the SearchView with following parameters.
`          mSearchView.setVersion(SearchView.VERSION_MENU_ITEM);
            mSearchView.setVersionMargins(SearchView.VERSION_MARGINS_MENU_ITEM);
            mSearchView.setTheme(SearchView.THEME_LIGHT, true);` 

You dont need to use the `app:actionViewClass` or ` app:actionLayout  ` instead you can open the searchview with SearchView.open(boolean,MenuItem) method as shown below.


` @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case R.id.menu_search:                
                    mSearchView.open(true, item);              
            default:               
        }
    return super.onOptionsItemSelected(item);
    }`

**Comment by lapism** [comment]
I hope there will be a new version 5.0.0-alpha1 after this weekend.

**Comment by jordaneckhardt** [comment]
Okay, I'll try that. 

Okay, that would be great! 

Thanks a lot for the help!
