### ISSUE TITLE
Implementation is not working

### ISSUE THREAD

**Issue by Dahnark** [lapism/SearchView#288]
I downloaded Android Studio 3.0 Canary 9 and updated the Gradle Plugin to 3.0.0-alpha9 and I can't implement the new version 5.0.0-alpha.

![image](https://user-images.githubusercontent.com/7463564/28992284-2181009e-7998-11e7-90cc-d087d8c834d0.png)

I tried implementation and compile.

**Comment by lapism** [comment]
I found out that has not been uploaded. I will fix it in next two days with a few bugs.

**Comment by CMathgician** [comment]
Hi @lapism, Is it solved?

**Comment by boswelja** [comment]
@CMathgician Try it and find out :P

**Comment by lapism** [comment]
Hi, I had to remove Bintray plugin because I had problems with uploading. I will fix it today or tomorrow.

**Comment by lapism** [comment]
It is out already.

**Comment by Dahnark** [comment]
This is not working:

implementation 'com.lapism:searchview:5.0.0-alpha1'

This is working:

implementation 'com.lapism.searchview:searchview:5.0.0-alpha1'

I got it from bintray:

https://i.imgur.com/xTIo9jT.png

**Comment by Dahnark** [comment]
Flexbox is giving me errors: 

`Error:(102) attribute 'com.mycompany.myapp:flexWrap' not found`

And a few more errors:

`Error:(1669, 71) error: cannot find symbol class OnItemClickListener`

`Error:(249, 41) error: cannot find symbol variable VERSION_MENU_ITEM
Error:(250, 48) error: cannot find symbol variable VERSION_MARGINS_MENU_ITEM
Error:(251, 39) error: cannot find symbol variable THEME_LIGHT
Error:(253, 58) error: cannot find symbol class OnVoiceClickListener`

**Comment by lapism** [comment]
I will fix it.

**Comment by lapism** [comment]
It has been heavily changed...please check the source code and I will add README soon.

**Comment by lapism** [comment]
setOnSearchItemClickListener and SearhView.Version.MENU_ITEM ...

**Comment by Dahnark** [comment]
But the flexwrap attribute?

**Comment by lapism** [comment]
probably u need use last version of flexbox 0.3.0

**Comment by Dahnark** [comment]
I haven't it installed, I should implement it?

**Comment by lapism** [comment]
No. If you are using FlexBox from google then you should use last version because my library uses this:
compile 'com.google.android:flexbox:0.3.0'

**Comment by Dahnark** [comment]
This text view ID what should be?

![image](https://user-images.githubusercontent.com/7463564/29094098-5eb28022-7c8c-11e7-8fe6-a83ea50f495d.png)

**Comment by lapism** [comment]
textView

**Comment by lapism** [comment]
I am sorry for these errors but I was working on it very long so it changed a lot.

**Comment by Dahnark** [comment]
Well, I can compile it, just changed 3 things (method, version, theme and versionmargin), but my app crashes.

Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #467: Error inflating class com.lapism.searchview.SearchView

Caused by: android.view.InflateException: Binary XML file line #467: Error inflating class com.lapism.searchview.SearchView

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lapism.searchview.SearchView" on path: DexPathList[[zip file ...

**Comment by lapism** [comment]
interesting. I will try it.

**Comment by Dahnark** [comment]
Some new about this?

**Comment by lapism** [comment]
yes. 5.0.0-alpha2 is out. I am working on it.

**Comment by lapism** [comment]
It has been done with Java8  so use this in your app gradle file
compileOptions {
    android.compileOptions.sourceCompatibility 1.8
    android.compileOptions.targetCompatibility 1.8
}

**Comment by lapism** [comment]
Ok, it seems like the FlexBox is source of problems...

**Comment by Dahnark** [comment]
@lapism I should try or wait? I was opening Android Studio hahah

**Comment by lapism** [comment]
You should wait...I did not know that new Gradle, Java8 and FlexBox will have a problem when they are together. But do not worry I am working on it.

**Comment by Dahnark** [comment]
FlexBox what is doing in the SearchView? I checked that it is a flex way to show views with different sizes, but I don't know where is applied in searchview

**Comment by lapism** [comment]
CheckBoxes for filtering.

**Comment by Dahnark** [comment]
@lapism ah, should be great that those check boxes can have on click listener, so when the user click them automatically it filters, without the necessary of the user insert text and touch search button

**Comment by lapism** [comment]
good idea. But right now I need to fix those bugs with FlexBox layout. Today I am going to work on it.

**Comment by Dahnark** [comment]
```
compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
}
```

I can't sync gradle with this part.

**Comment by Dahnark** [comment]
Well after 23132312837213 Clean Project and 233123123 Rebuild Project, Android Studio has decided to work!

I am going to test it, the app is working and the SearchView doesn't crash when I use it.

**Comment by lapism** [comment]
I am happy to hear that ... I would like to fix everything before stable release.

**Comment by Dahnark** [comment]
@lapism personally I found this bug https://github.com/lapism/SearchView/issues/293

All is working perfectly and (at this moment) I haven't received more ACRA reports related to the SearchView.

**Comment by lapism** [comment]
I will fix it in next iteration...
