### ISSUE TITLE
setSelection method

### ISSUE THREAD

**Issue by AngleV** [lapism/SearchView#289]
is it possible to add a mSearchView.setSelection method ????

**Comment by boswelja** [comment]
And what would that method do?

**Comment by AngleV** [comment]
https://developer.android.com/reference/android/text/Selection.html#setSelection(android.text.Spannable, int, int)

**Comment by boswelja** [comment]
I see.. and how would that be useful? Why can't the user just select text on their own

**Comment by lapism** [comment]
I do not know why I should add a new feature without released stable version 5.0.0. So maybe in future ...
