### ISSUE TITLE
Suggestion list doesn't show elements before first search.

### ISSUE THREAD

**Issue by Dahnark** [lapism/SearchView#293]
In 5.0.0-alpha3 my suggestion list is empty, then when I search some name, the next time the suggestion list show all items.

How can I change the list to show only items that start with the inserted text and not that containt the text.

Is it possible to change the fade effect of the suggestion list items?

**Comment by Dahnark** [comment]
I am still unable to get my suggestion list in the first search, I provocated this bug in my code or anyone more have it?

**Comment by lapism** [comment]
This bug is part of new bugs in SearchAdapter ... I want to fix it in this week.

**Comment by Dahnark** [comment]
Okay! Can you add this:

"@lapism ah, should be great that those check boxes can have on click listener, so when the user click them automatically it filters, without the necessary of the user insert text and touch search button"

To a feature request list?

**Comment by lapism** [comment]
Yes, it is already there +1:
