### ISSUE TITLE
Implementing Suggestions/Search History

### ISSUE THREAD

**Issue by ItsCalebJones** [lapism/SearchView#295]
Hey there,

Looks like there is no Sample with this project, however there was at one point? Perhaps would be a good time to add some implementation details in the readme. I'm struggling attempting to implement the search history here, even with reading the source code.

**Comment by lapism** [comment]
I am sorry. Better README will be ASAP...

**Comment by lapism** [comment]
Added. But I will improve it in future.

**Comment by ItsCalebJones** [comment]
Thanks! Great library.
