### ISSUE TITLE
Search in v5.0-alpha3 is too slow compared to v3.8

### ISSUE THREAD

**Issue by HusseinElFeky** [lapism/SearchView#297]
I was using SearchView v3.8 before and everything was working great as expected, but when I updated to SearchView v5.0-alpha3, I encountered many issues.

One of them is that searching now is a lot more slower than before, and it updates the results list too late. My query can reach over 80,000 search items, so it takes much time to filter the query each time the text in SearchEditText is changed (I let it update the results each time text is changed). In v3.8 as I said, it was fast and smooth, but in v5.0-alpha3, it's too slow now. Why?

I noticed a new fade animation between each query change in v5.0-alpha3. Can that be the problem? If yes, can you add an option to disable that fade animation to let the search be more faster for those who always use big queries? If that's not the issue, what can it be?

Can you compare between v3.8 and v5.0-alpha3 to understand the issue?

**Comment by lapism** [comment]
Yes, I understand. This version is still ALPHA, but I will take a look on comparison between those two versions.

**Comment by HusseinElFeky** [comment]
Alright, thanks, looking forward to it!

**Comment by lapism** [comment]
I hope I will fix it in next version Alpha5.

**Comment by lapism** [comment]
Could you try Alpha4?

**Comment by HusseinElFeky** [comment]
I tested alpha4, but unfortunately there was no difference. :/

1. You removed Java8 requirement, which is great. 👍

2. The searching speed is still the same though. I counted my search items, and it turned to be 128,783 search items exactly, which is really really very huge, I know. But in v3.8, it was fast and there was no problem with that, so I think the fade animation is the problem (I'm not sure though, I don't know what's changed in the code). Can you maybe try to create a random list that generates about 130,000 search items and test that yourself? :)

PS: I create that list `onCreate()` in a new thread to prevent lag on the main thread, but after the for loop is done executing, I set the adapter to the SearchView in that same new thread. It doesn't take very long time anyway (about 2 seconds or less only). I don't have an issue with the adapter creation but rather the searching speed. Sometimes my device even freezes... If you want me to send a video demonstrating my issue and showing the difference of searching speed between v3.8 and v5.0-alpha4 to your email or something, I can do that. Just tell me, and I can record it for you. :)

3. Another small issue is that sometimes the search items are shown even when the SearchEditText is empty. I don't want any search items to be shown when the SearchEditText is empty because it will return 128,783 search items, which will really be useless and consumes much memory.

4. And still `setNavigationIconAnimation()` doesn't work. I implemented a fix for this in a new pull request but you declined to merge it. I don't know why. Shouldn't `mArrow` be set to `!animate`? I didn't test it honestly, but I noticed that when I don't call `setNavigationIconAnimation()`, the arrow animation is still there, while when I call it and set `animate` to true or false, in both cases the animation gets removed ignoring the `animate` value, and when I saw the default value for `animate`, it is false, and it doesn't get changed except in `setNavigationIconAnimation()`. So shouldn't it be set to `!animate`?

**Comment by lapism** [comment]
1. We needed Java 8 in our project but I decided to remove it because only a few people use it only.
2. I checked last commit before release of 3.8 and I am trying to find out what has been changed in Adapter and can cause this speed problems.
3. I will check it.
4. This is in TODO for next version.

**Comment by HusseinElFeky** [comment]
Ok awesome, waiting for it :)

**Comment by lapism** [comment]
@HusseinElFeky tomorrow I hope.

**Comment by HusseinElFeky** [comment]
For some reason, Android Studio says "Failed to resolve: com.lapism:searchview:5.0.0-alpha5".

**Comment by lapism** [comment]
Why ? It has not been uploded yet. Tomorrow maybe.

**Comment by HusseinElFeky** [comment]
Yeah, if it's not uploaded yet, then that's the reason. No worries. Great.

**Comment by Dahnark** [comment]
@lapism is it uploading yet? Bintray show alpha 4.

**Comment by lapism** [comment]
Today or tomorrow ;).

**Comment by HusseinElFeky** [comment]
@lapism Any news?

**Comment by lapism** [comment]
This weekend I hope. I did not have a time.

**Comment by HusseinElFeky** [comment]
Ok, thanks. No problem. :)

**Comment by boswelja** [comment]
@lapism have you considered collaborating with other people to get releases out sooner?
I know pull requests are enabled, but most people just tend to make a new issue

**Comment by lapism** [comment]
@boswelja no I have not. You are right, people still open new issues but only a few of them send a pull request with bugfix. And because I have a job and family I do not have much time for fixing everything.

**Comment by HusseinElFeky** [comment]
Issues #2 and #3 are the only ones left in this query. I have fixed the others. I will start working on them when I have time probably next week though if they are not fixed yet. :)

**Comment by HusseinElFeky** [comment]
Issues 2 and 3 are the only ones left in this query. I have fixed the others. I will start working on them when I have time probably next week though if they are not fixed yet. :)

**Comment by HusseinElFeky** [comment]
I have finally fixed all the issues mentioned here, so I will close this issue once my pull request gets approved.

**Comment by HusseinElFeky** [comment]
I have finally fixed all the issues mentioned here, so I will close this issue once my pull request gets merged.
