### ISSUE TITLE
Version 2 - migration/changes/...

### ISSUE THREAD

**Issue by Rainer-Lang** [lapism/SearchView#30]
Hi,
You write that 1.5 isn't compatible to the new 2.0
Do we devs have to do something for migration? Is there something big different/missing in 2.0?
Or other way: What is the big advantage of the new version?

Please give us a few information. :)

**Comment by lapism** [comment]
Hi. I will do it soon. Thanks. Mainly a few methods have changed names. Check sample project.

**Comment by lapism** [comment]
And what you think about new version? Do you like it?

**Comment by Rainer-Lang** [comment]
I opened the google play version - seems the same. 
The project sample I will try today.

**Comment by lapism** [comment]
yes, it is. Almost :)

**Comment by Rainer-Lang** [comment]
YES - almost :-D :+1: You're kidding. 

Great work!

**Comment by lapism** [comment]
Of course :P. Thank you

**Comment by Rainer-Lang** [comment]
I'm just thinking about to include the SearchView not only in Toolbar but also as a search-field in a fragment. Do you think this could work? But therefore I have to hide the "nav-drawer"-icon (3 lines).

**Comment by lapism** [comment]
I am not really sure about that. You can try.
But I know one thing about voice search. Button is searching instance of activity, so for you and me it is only one possibility. That I should add instance of fragment and v4.fragment in next release :D. And fix that permission thing on API 23.

**Comment by Rainer-Lang** [comment]
Would be great :-D

**Comment by lapism** [comment]
Neverending work. And add CoordinatorLayout.Behavior, cause I would like to have layout like main screen in Play Store.

**Comment by Rainer-Lang** [comment]
Ending? Work? => NEVER! ;-)

**Comment by lapism** [comment]
public void setVoice with Activity, v4.Fragment, Fragment added. Still version 2.0.1, just reuploaded. You can try if it works in Fragments.

**Comment by stormtheh4ck3r** [comment]
nice work dude!

**Comment by lapism** [comment]
Thanks
