### ISSUE TITLE
Inflate error

### ISSUE THREAD

**Issue by debjitk** [lapism/SearchView#300]
I am getting the following error ... 

Binary XML file line #9: Error inflating class com.lapism.searchview.SearchView

Much down the stack trace ... I also have an error like ..

Didn't find class "com.google.android.flexbox.FlexboxLayout"

**Comment by Dahnark** [comment]
implement by yourself flexbox 0.3.0 by google.

`dependencies {
    compile 'com.google.android:flexbox:0.3.0'
}`

**Comment by lapism** [comment]
More in #298
