### ISSUE TITLE
SearchAdapter does not show any suggestions

### ISSUE THREAD

**Issue by atar9500** [lapism/SearchView#302]
Hello,

I'm trying to show suggestions for places whenever the user types text into the SearchView, but currently the SearchAdapter doesn't seem to show any suggestions at all.
Please help me solve this issue, what am I doing wrong?

I'm currently using com.lapism:searchview:5.0.0-alpha4

Fragment:

`searchPlace = (SearchView) v.findViewById(R.id.search_place);
        searchPlace.setHint("Restaurants in Tel Aviv");
        searchPlace.setVersion(SearchView.VersionMargins.TOOLBAR_SMALL);

        mSuggestions = new ArrayList<SearchItem>();
        mPlacesIDs = new ArrayList<>();
        adapter = new SearchAdapter(getContext(), mSuggestions);
        searchPlace.setAdapter(adapter);
        adapter.setOnSearchItemClickListener(new SearchAdapter.OnSearchItemClickListener() {
            @Override
            public void onSearchItemClick(View view, int position) {
                searchPlace.setQuery(suggestions.get(position).getText(), false);
                String id = placesIDs.get(position);
                mGeoDataClient.getPlaceById(id).addOnCompleteListener(new OnCompleteListener<PlaceBufferResponse>() {
                    @Override
                    public void onComplete(@NonNull Task<PlaceBufferResponse> task) {
                        if (task.isSuccessful()) {
                            PlaceBufferResponse places = task.getResult();
                            Place place = places.get(0);
                            latitude = place.getLatLng().latitude;
                            longitude = place.getLatLng().longitude;
                            MarkerOptions markerOptions = new MarkerOptions()
                                    .position(place.getLatLng())
                                    .title(place.getName().toString())
                                    .snippet(place.getAddress().toString());
                            goToLocation(place.getLatLng(), markerOptions, 13);
                            places.release();
                            mSuggestions.clear();
                            mPlacesIDs.clear();
                            adapter.notifyDataSetChanged();
                            searchPlace.close(true);
                        } else {
                            Log.e(TAG, "Place not found.");
                        }
                    }
                });
            }
        });
        searchPlace.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
            @Override
            public boolean onQueryTextChange(String newText) {
                mGeoDataClient.getAutocompletePredictions(newText,
                        new LatLngBounds(new LatLng(-90, -180), new LatLng(90, 180)), null)
                        .addOnCompleteListener(new OnCompleteListener<AutocompletePredictionBufferResponse>() {
                            @Override
                            public void onComplete(@NonNull Task<AutocompletePredictionBufferResponse> task) {
                                mSuggestions.clear();
                                mPlacesIDs.clear();
                                adapter.notifyDataSetChanged();
                                if(task.isSuccessful()){
                                    AutocompletePredictionBufferResponse places = task.getResult();
                                    for (Iterator<AutocompletePrediction> i = places.iterator();
                                         i.hasNext();) {
                                        AutocompletePrediction predict = i.next();
                                        String fullText = predict.getFullText(null).toString();
                                        String id = predict.getPlaceId();
                                        SearchItem suggestion = new SearchItem(fullText);
                                        mPlacesIDs.add(id);
                                        mSuggestions.add(suggestion);
                                        adapter.notifyItemInserted(suggestions.size() - 1);
                                    }
                                    places.release();
                                } else {
                                    searchPlace.close(true);
                                    Log.e(TAG, "Place not found.");
                                }
                            }
                        });
                return false;
            }

            @Override
            public boolean onQueryTextSubmit(String query) {
                if(!query.equals("")){
                    mSuggestions.clear();
                    mPlacesIDs.clear();
                    adapter.notifyDataSetChanged();
                    searchPlace.close(true);
                    Geocoder geocoder = new Geocoder(getActivity());
                    List<Address> addresses = null;
                    try {
                        addresses = geocoder.getFromLocationName(query, 10);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                    if(addresses != null && addresses.size() != 0) {
                        for(int j = 0; j < addresses.size(); j++){
                            latitude = addresses.get(j).getLatitude();
                            longitude = addresses.get(j).getLongitude();
                            LatLng lng = new LatLng(latitude, longitude);
                            MarkerOptions markerOptions = new MarkerOptions()
                                    .position(lng)
                                    .title(addresses.get(j).getLocality())
                                    .snippet(addresses.get(j).getSubLocality());
                            goToLocation(lng, markerOptions, 13);
                        }
                    }
                }
                return false;
            }
        });`

XML:

`<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment
        android:id="@+id/map"
        android:name="com.google.android.gms.maps.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        tools:context="com.atar.presto.ui.MapsActivity"/>

    <com.lapism.searchview.SearchView
        android:id="@+id/search_place"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="com.lapism.searchview.SearchBehavior"/>

</android.support.design.widget.CoordinatorLayout>`

**Comment by HusseinElFeky** [comment]
About how many suggestions are there in your SearchAdapter?

**Comment by atar9500** [comment]
I'm getting my suggestions from google place autocomplete api, so it's about 5 suggestions max

**Comment by Dahnark** [comment]
there is a known bug that the first search doesn't show suggestions, the second search for me starts to show suggestions

**Comment by lapism** [comment]
@HusseinElFeky No, I have not had time for this yet. ASAP.

**Comment by HusseinElFeky** [comment]
@atar9500 Try using v5.0.0-alpha6. It is fixed.
