### ISSUE TITLE
Can't download library in gradle

### ISSUE THREAD

**Issue by monajafi** [lapism/SearchView#303]
Hi
After syncing gradle I faced with following error which is related to library gradle link:
Error:(43, 20) Failed to resolve: com.lapism:searchview:5.0.0-alpha5
I upgraded android studio to version 3 preview beta 4 and gradle to version 3 but I coudln't solve problem
alpha4 get downloaded without problem

**Comment by HusseinElFeky** [comment]
Yeah, that happens because version 5.0.0-alpha5 is not uploaded to bintray yet. It was only updated in README.md before it got uploaded. @lapism said he will upload it this weekend. For now you will have to use version 5.0.0-alpha4.

**Comment by monajafi** [comment]
Thanks a lot

**Comment by lapism** [comment]
Yes. I forgot. I will upload it this weekend.
