### ISSUE TITLE
Dynamically switching between TOOLBAR and MENU_ITEM vesions

### ISSUE THREAD

**Issue by AlexeyGorovoy** [lapism/SearchView#311]
I currently see a problem with that. 

All my fragments have a search view in a MENU_ITEM version, but I want it to be available as a TOOLBAR on the one specific fragment. So I just switch versions.  like this:

        // search view in defined in main activity and all fragments access it. 
        // any fragment
        version = SearchView.Version.MENU_ITEM
        versionMargins = SearchView.VersionMargins.MENU_ITEM
        setTheme(SearchView.Theme.LIGHT, true)
        // `special` fragment
        version = SearchView.Version.TOOLBAR
        versionMargins = SearchView.VersionMargins.TOOLBAR_BIG
        setTheme(SearchView.Theme.LIGHT, true)

But here's a problem. If I open and close a SearchView on the 'normal' fragment, it's hidden when I open the 'special' fragment.

So I tried just to set `searchView.visibility = View.VISIBLE` in the 'special' fragment, but that's not gonna work because `searchView` has a `cardView` inside it which is also get's hidden in a `close()` method.

I guess SearchView should take things like this in a `setVersion()` method and reset state according to the requested version.

Or it's just the wrong way to implement this? Should my 'special' fragment have a separate instance of 
 a search view?

**Comment by lapism** [comment]
Have you tried .invalidate()?

**Comment by AlexeyGorovoy** [comment]
I had a thought to try it, but it looks like the call to 'searchView.invalidate()' will invoke the default implementation.  I mean SearchView doesn't override it from the `View` class.

Given you're an author of the lib, I guess I should try it, shouldn't I?)

**Comment by lapism** [comment]
Yes, it will be default but you can setVersion after that. It should be functional, but if it does not work I will fix it ASAP.

**Comment by AlexeyGorovoy** [comment]
That doesn't seem to work.

After an `invalidate()` call both `searchView` and `mCardView` (the inner variable of a `SearchView`) remain in `GONE` state and nothing is visible to the user. 

And while I'm able to call `searchView.visibility = VISIBLE`, it still gets me nothing as I can't access private 'mCardView'.

Proper steps to reproduce, if you decide to investigate the issue:
- init search view as a `MENI_ITEM`
- do some actions so that `open()` and then `close()` will be invoked on that view
- change version `TOOLBAR`

I'm still not sure if the view should support such behavior change in runtime, it's up to you.  

I decided to handle my issue in following way - I have now a separate search view instance for all my fragments but one. The 'special' fragment has its own instance. Works fine so far.
