### ISSUE TITLE
Unable to compile gradle

### ISSUE THREAD

**Issue by Shubhraaaj** [lapism/SearchView#313]
I have used this in my app.gradle

compileSdkVersion 26
    buildToolsVersion "26.0.1"

    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.lapism:searchview:5.0.0-alpha6'
    compile 'com.android.support:cardview-v7:26.0.2'
    compile 'com.google.android:flexbox:0.3.0'

But there are four errors:-
Error:Failed to resolve: com.android.support:appcompat-v7:26.0.2
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile:C:/Users/shubh/Desktop/Android/Prototype/app/build.gradle">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by EmmanuelMess** [comment]
Try with 26.0.1

**Comment by HusseinElFeky** [comment]
Try changing
`com.android.support:appcompat-v7:26.+`
to
`com.android.support:appcompat-v7:26.0.2`

**Comment by Shubhraaaj** [comment]
I tried them all. but still it gives the same error and even I cannot Install Repository and Sync project

**Comment by EmmanuelMess** [comment]
You have `buildToolsVersion "26.0.1"` and `compile 'com.android.support:cardview-v7:26.0.2'` and `compile 'com.android.support:appcompat-v7:26.+'` choose a vesion (26.0.1 or 26.0.2) and stick (explicitly to it).

**Comment by HusseinElFeky** [comment]
@EmmanuelMess That won't matter. `buildToolsVersion` is different from Android support libraries. I use it like that, and it works. @Shubhraaaj Can you post all your `build.gradle` code?

**Comment by Shubhraaaj** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.example.shubhraj.prototype"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.miguelcatalan:materialsearchview:1.4.0'
    testCompile 'junit:junit:4.12'
}

**Comment by Dahnark** [comment]
You have to add cardview and flexbox dependencies.

You are using miguel catalan material search view in your last comment, this is not that searchview library.

```
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'com.google.android:flexbox:0.3.0'
    compile 'com.android.support:cardview-v7:26.0.2'
```
And in build tools version:   `  buildToolsVersion "26.0.1"`

**Comment by HusseinElFeky** [comment]
Yeah, the issue should be closed now.

**Comment by lagoren** [comment]
hi i have the same problem, this solution didn't work for me..
can anyone help me with that? this is my app.gradle file:


apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.example.galgoren.finalproject"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'com.android.support:cardview-v7:26.0.2'
    compile 'com.google.android.gms:play-services-maps:11.0.4'
    compile 'com.squareup.picasso:picasso:2.3.2'
    testCompile 'junit:junit:4.12'


}

**Comment by Dahnark** [comment]
@lagoren your dependencies{} doesn't have the 3 dependencies required. You don't even have the SearchView dependency so I don't understand how you are having this problem :/

**Comment by lagoren** [comment]
hey thanks for replaying this is my gradle when it works :) i tried to do this and got an error:


apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.example.galgoren.finalproject"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'com.android.support:cardview-v7:26.0.2'
    compile 'com.google.android.gms:play-services-maps:11.0.4'
    compile 'com.squareup.picasso:picasso:2.3.2'
    testCompile 'junit:junit:4.12'

    compile 'com.google.android:flexbox:0.3.0'
    compile 'com.lapism:searchview:5.0.0-alpha6'

}

**Comment by HusseinElFeky** [comment]
Use alpha7, it's released, although that's still not the reason. What error do you get?

**Comment by lagoren** [comment]
Failed to resolve: com.lapism:searchview:5.0.0-alpha6

**Comment by lagoren** [comment]
just used alpha7 and it did not give me errors, trying it right now ..thank you!

**Comment by Dahnark** [comment]
Update all dependencies, then clean and rebuild the project.

**Comment by Dahnark** [comment]
@lagoren https://bintray.com/lapism/maven/searchview/view

alpha6 is not there.

**Comment by lagoren** [comment]
after changing it to alpha7 it seems to work thank you! 

but when im trying to find the view i get an error:

SearchView cannot be cast to android.support.v7.widget.SearchView
                                                                                     at com.example.galgoren.finalproject.MainActivity.onCreate(MainActivity.java:74)

**Comment by Dahnark** [comment]
have you added the view to the layout?

**Comment by lagoren** [comment]
this is my onCreate at MainActivity:

package com.example.galgoren.finalproject;


import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Build;
import android.os.Bundle;
import android.support.design.widget.TabLayout;
import android.support.v4.app.Fragment;
import android.support.v4.content.LocalBroadcastManager;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.SearchView;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

import com.example.galgoren.finalproject.adapters.MyFragmentAdapter;
import com.example.galgoren.finalproject.adapters.MyListAdapter;
import com.example.galgoren.finalproject.db.PlacesProvider;
import com.example.galgoren.finalproject.fragments.FragmentFavorite;
import com.example.galgoren.finalproject.fragments.FragmentMainSearch;
import com.example.galgoren.finalproject.model.Place;

import java.util.List;

public class MainActivity extends AppCompatActivity implements TabLayout.OnTabSelectedListener, MyListAdapter.OnMyClickListener, MyBatteryReceiver.OnBatteryChangedListener {


    private MyFragmentAdapter myFragmentAdapter;
    private ViewPager pager;
    private MyBatteryReceiver receiver;
    private SearchView searchWord;
    private GooplePlacesReceiver googlePlacesReceiver;
    private FragmentFavorite fragmentFavorite;


    //-----------------------------------------------------------------------------


    // onCreate
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        // listening with the receiver to the googleSearchService
        googlePlacesReceiver = new GooplePlacesReceiver();
        LocalBroadcastManager.getInstance(this).registerReceiver(googlePlacesReceiver, new IntentFilter
                (IntentServiceGooglePlaces.ACTION_GOOGLEPLACES));


        // registering and connecting to battery receiver
        receiver = new MyBatteryReceiver(this);
        IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(Intent.ACTION_POWER_CONNECTED);
        intentFilter.addAction(Intent.ACTION_POWER_DISCONNECTED);
        registerReceiver(receiver, intentFilter);


        // setting the toolbar
        Toolbar myToolBar = (Toolbar) findViewById(R.id.myToolBar);
        setSupportActionBar(myToolBar);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            myToolBar.setOverflowIcon(getDrawable(R.mipmap.ic_menu_icon_white));
        }

        // finding the search view
       searchWord = findViewById(R.id.searchView);


        // connecting the fragments to the view pager and displaying search fragment
        myFragmentAdapter = new MyFragmentAdapter(getSupportFragmentManager());
        pager = (ViewPager) findViewById(R.id.pager);
        pager.setAdapter(myFragmentAdapter);

        pager.setCurrentItem(1);

        // connecting the tabLayout to the pager
        TabLayout tabs = (TabLayout) findViewById(R.id.tabLayout);
        tabs.setupWithViewPager(pager);

        fragmentFavorite = (FragmentFavorite) myFragmentAdapter.getItem(0); // it falls here


    }

**Comment by lagoren** [comment]
yes here is my activity_main.xml


<?xml version="1.0" encoding="utf-8"?>
<android.widget.RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.galgoren.finalproject.MainActivity">



    <android.support.v7.widget.Toolbar
        android:id="@+id/myToolBar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_centerVertical="true"
        android:background="?attr/colorPrimary"
        android:minHeight="?attr/actionBarSize"
        android:theme="?attr/actionBarTheme">


        <com.lapism.searchview.SearchView
            android:id="@+id/searchView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="com.lapism.searchview.SearchBehavior" />



    </android.support.v7.widget.Toolbar>

    <android.support.design.widget.TabLayout
        android:id="@+id/tabLayout"
        app:tabGravity="fill"
        app:tabMaxWidth="0dp"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        android:layout_below="@id/myToolBar"
        android:background="@color/colorPrimary"
        app:tabTextColor="@color/cardview_light_background">

        <android.support.design.widget.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="FAV" />

        <android.support.design.widget.TabItem
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="SEARCH" />

    </android.support.design.widget.TabLayout>

    <view
        android:id="@+id/pager"
        class="android.support.v4.view.ViewPager"
        id="@+id/view"
        layout_alignParentLeft="true"
        layout_alignParentStart="true"
        layout_alignParentTop="true"
        layout_marginLeft="11dp"
        layout_marginStart="11dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_below="@+id/tabLayout" />

</android.widget.RelativeLayout>

**Comment by lagoren** [comment]
and my MainActivity onCreate:


package com.example.galgoren.finalproject;


import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Build;
import android.os.Bundle;
import android.support.design.widget.TabLayout;
import android.support.v4.app.Fragment;
import android.support.v4.content.LocalBroadcastManager;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.SearchView;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Toast;

import com.example.galgoren.finalproject.adapters.MyFragmentAdapter;
import com.example.galgoren.finalproject.adapters.MyListAdapter;
import com.example.galgoren.finalproject.db.PlacesProvider;
import com.example.galgoren.finalproject.fragments.FragmentFavorite;
import com.example.galgoren.finalproject.fragments.FragmentMainSearch;
import com.example.galgoren.finalproject.model.Place;

import java.util.List;

public class MainActivity extends AppCompatActivity implements TabLayout.OnTabSelectedListener, MyListAdapter.OnMyClickListener, MyBatteryReceiver.OnBatteryChangedListener {


    private MyFragmentAdapter myFragmentAdapter;
    private ViewPager pager;
    private MyBatteryReceiver receiver;
    private SearchView searchWord;
    private GooplePlacesReceiver googlePlacesReceiver;
    private FragmentFavorite fragmentFavorite;


    //----------------------------------------------------------------------------------------------


    // onCreate
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);


        // listening with the receiver to the googleSearchService
        googlePlacesReceiver = new GooplePlacesReceiver();
        LocalBroadcastManager.getInstance(this).registerReceiver(googlePlacesReceiver, new IntentFilter
                (IntentServiceGooglePlaces.ACTION_GOOGLEPLACES));


        // registering and connecting to battery receiver
        receiver = new MyBatteryReceiver(this);
        IntentFilter intentFilter = new IntentFilter();
        intentFilter.addAction(Intent.ACTION_POWER_CONNECTED);
        intentFilter.addAction(Intent.ACTION_POWER_DISCONNECTED);
        registerReceiver(receiver, intentFilter);


        // setting the toolbar
        Toolbar myToolBar = (Toolbar) findViewById(R.id.myToolBar);
        setSupportActionBar(myToolBar);

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            myToolBar.setOverflowIcon(getDrawable(R.mipmap.ic_menu_icon_white));
        }

        // finding the search view
       searchWord = findViewById(R.id.searchView);       **// it falls here**


        // connecting the fragments to the view pager and displaying search fragment
        myFragmentAdapter = new MyFragmentAdapter(getSupportFragmentManager());
        pager = (ViewPager) findViewById(R.id.pager);
        pager.setAdapter(myFragmentAdapter);

        pager.setCurrentItem(1);

        // connecting the tabLayout to the pager
        TabLayout tabs = (TabLayout) findViewById(R.id.tabLayout);
        tabs.setupWithViewPager(pager);

        fragmentFavorite = (FragmentFavorite) myFragmentAdapter.getItem(0);


    }

**Comment by HusseinElFeky** [comment]
You imported the wrong class. Replace `import android.support.v7.widget.SearchView;` with `import com.lapism.searchview.SearchView;`.

**Comment by lagoren** [comment]
thank you!

**Comment by lagoren** [comment]
i was trying for couple of hour to hide suggestions, when i click on the search view an empty blue menu is opened, i tried: searchBar.hideSuggestions(); and it didnt work

**Comment by lagoren** [comment]
hi 

im geting an error: 

Failed to resolve: com.lapism:searchview:5.0.0-alpha6

this is my build.gradle:


apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.example.galgoren.finalproject"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.0.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:26.0.2'
    compile 'com.android.support:design:26.0.2'
    compile 'com.google.android:flexbox:0.3.0'
    compile 'com.android.support:cardview-v7:26.0.2'
    compile 'com.google.android.gms:play-services-maps:11.0.4'
    compile 'com.squareup.picasso:picasso:2.3.2'
    testCompile 'junit:junit:4.12'


    compile 'com.google.android:flexbox:0.3.0'
    compile 'com.lapism:searchview:5.0.0-alpha6'

    compile 'com.github.mancj:MaterialSearchBar:0.7.5'

}

**Comment by lapism** [comment]
@lagoren  implementation 'com.lapism:searchview:27.1.1.0.0'
