### ISSUE TITLE
Please provide sample app.

### ISSUE THREAD

**Issue by Shubhraaaj** [lapism/SearchView#314]
Please provide code for a sample app that implements search using this library.

**Comment by boswelja** [comment]
No, it was removed as it was out of date

**Comment by HusseinElFeky** [comment]
You can check the sample code in README.md. Not all features are written there, but the most common ones are written. If you want to know about the other features, you should check the source code itself.

**Comment by lapism** [comment]
If you use the third party library then you should be able to do almost everything by yourself. The library is very simple  so you do not need whole sample for it.
