### ISSUE TITLE
Black translucent background doesn't have animation at first open of SearchView

### ISSUE THREAD

**Issue by Dahnark** [lapism/SearchView#318]
The first time that I open the SearchView doesn't show the animation of the black translucent background. But the next time I open it starts to show this animation.

This bug is in alpha7 but I think that it was in previous alpha versions.

**Comment by HusseinElFeky** [comment]
Yeah, it was also in previous alpha versions.

**Comment by lapism** [comment]
Maybe. And this is the reason why from now I will not accept any kind of pull request because I want to test everything by myself when I will have more time. And after that I will release it.

**Comment by HusseinElFeky** [comment]
@lapism That issue was there since at least `v5.0.0-alpha3`. That was the first version I tried in the alpha versions of version 5, so it might have even been there since alpha1. So you should check the changes from alpha version 3 and below.

**Comment by HusseinElFeky** [comment]
@lapism That issue was there since at least `v5.0.0-alpha3`. That was the first version I tried in the alpha versions of version 5, so it might have even been there since alpha1. So to save time for you, you can check the changes from alpha version 3 and below.
