### ISSUE TITLE
SearchBar not hide with Back Keydown

### ISSUE THREAD

**Issue by loaloel** [lapism/SearchView#32]
Please help me sir,
Im using Menu Item Version
When im use back icon on the search bar, SearchView hide normal.
When im just click on the background, SearchView hide normal.
but when im using Back Keydown, it just hide the focus, not the search bar.
also it happen on the sample library.
im using Infinix Android One with OS Lolipop right now.
sorry for my poor english.

**Comment by lapism** [comment]
I know about that bug. It will be fixed today or tomorrow.

**Comment by lapism** [comment]
fixed
