### ISSUE TITLE
Wrong ripple effect on the hamburger icon

### ISSUE THREAD

**Issue by feinstein** [lapism/SearchView#330]
The ripple effect on the hamburger icon should be rounded and not squared...I know this can be achieved using the `?android:attr/selectableItemBackgroundBorderless` (Lollipop+) as the background, but I didn't check the code to be sure what you are using.

Here's how's supposed to be (Google Maps):
![image](https://user-images.githubusercontent.com/8120472/32191583-bd7f7626-bd98-11e7-963a-314958430bda.png)

Here's how it's on my app using the `SearchView`:
![image](https://user-images.githubusercontent.com/8120472/32191544-9ea8a998-bd98-11e7-8e99-8f17f34bd70e.png)
__________
EDIT:
I just realized the same hols true for all the other icons ('X' and the microphone icon).

**Comment by Dahnark** [comment]
I think it can be solved using `selectableItemBackgroundBorderless` instead of using `selectableItemBackground`.

**Comment by boswelja** [comment]
@Dahnark that would be correct, wanna open up a PR that fixes this?

**Comment by Dahnark** [comment]
@boswelja I checked the source code and I think it is using borderless now...

**Comment by boswelja** [comment]
@Dahnarkyou what happens if you set clipToPadding to false?

**Comment by lapism** [comment]
It is fixed in my private repository now. It should used background instead of foreground attribute.
