### ISSUE TITLE
How to force the Hamburger Icon animation?

### ISSUE THREAD

**Issue by feinstein** [lapism/SearchView#333]
I want the Hamburger icon to animate to an arrow when its clicked, to open the `NavigationDrawer`, just like the `toolbar` does in an `AppBar`.

Can I force this animation?

In a `toolbar` the hamburger icon and the `NavigationDrawer` are interlinked, the further you open the `NavigationDrawer`, the further the hamburger icon spins....is this possible to be achieved?

**Comment by lapism** [comment]
In next version there will be a new method : animateHamburgerToArrow(true or false);
