### ISSUE TITLE
Make the search results views editable 

### ISSUE THREAD

**Issue by feinstein** [lapism/SearchView#336]
After trying to use this library for a while I find it kinda limited.

I wanted to be able to provide my own `ReciclerView.Adapter` but I am limited on fitting my data to a `SearchItem`, and not my own `View`. For this reason I am reconsidering using the library unfortunately.

**Comment by lapism** [comment]
I am open to every pull request ...

**Comment by feinstein** [comment]
I am open to code something as well, but as far as I can see the code is too tight to this implementation and this will take too much effort to implement, the lack of documentation also slows me down a lot to understand what has to be changed and the effects will be.

I will try to figure something out and if I can't find any other choice I will try to submit some PR.

**Comment by feinstein** [comment]
@lapism I will try to take a look at this but for now I can't because of  #335.
