### ISSUE TITLE
v5.0.0-alpha7 error showing searchview under toolbar 

### ISSUE THREAD

**Issue by jaksab** [lapism/SearchView#338]
Hi. Thanks for this library!
Yesterday I was update library to 5.0.0-alpha7 and now searchview is showing under toolbar.
Main layout - CoordinatorLayout.
Searchview and margins type - menu item.
AppCompat version: 27.0.1.
I call searchview.open(true).

I try configure searchview in xml or code, with behaviour - no results. When I disable toolbar searchview is showing. 

Screenshot https://www.dropbox.com/s/2a3yvqo634yyi1z/Screenshot_20171120-083843.png?dl=0

**Comment by jaksab** [comment]
I solved this problem as follows:

```
public class MySearchViewBehavior extends CoordinatorLayout.Behavior<SearchView> {
    public MySearchViewBehavior() {
        super();
    }
    public MySearchViewBehavior(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean layoutDependsOn(CoordinatorLayout parent, SearchView child, View dependency) {
        if (dependency instanceof AppBarLayout) {
            ViewCompat.setElevation(child, ViewCompat.getElevation(dependency));
            ViewCompat.setZ(child, ViewCompat.getZ(dependency) + 1);
            return true;
        }
        return super.layoutDependsOn(parent, child, dependency);
    }

    @Override
    public boolean onDependentViewChanged(CoordinatorLayout parent, SearchView child, View dependency) {
        if (dependency instanceof AppBarLayout) {
            child.setTranslationY(dependency.getY());
            return true;
        }
        return super.onDependentViewChanged(parent, child, dependency);
    }
}
```

I think it happened in the new version of AppCompat, AppBar has a priority Z-coordinate

**Comment by lapism** [comment]
Can you send me a pull request with these changes for SearchBehavior in library ?:)

**Comment by lapism** [comment]
I am working on Beta1 which will be released probably next week.

**Comment by lapism** [comment]
Fixed in private repository >> future Beta1
