### ISSUE TITLE
Couldn't Change the shadow background color to semi transparent

### ISSUE THREAD

**Issue by Devspm** [lapism/SearchView#343]
Don't know how to change the shadow background color to semi-transparent ,only getting solid color

I wanted to change this 

![capture](https://user-images.githubusercontent.com/34958091/34453045-f2897da0-ed70-11e7-9580-aa0e251bd225.PNG)

to 
![image_2 1](https://user-images.githubusercontent.com/34958091/34453069-3af660bc-ed71-11e7-9432-4c0ba83b7434.png)

**Comment by lapism** [comment]
There should be :
    public void setShadowColor(@ColorInt int color) {
        mViewShadow.setBackgroundColor(color);
    }
