### ISSUE TITLE
[Marshmallow] 1st tap on button doesn't animate

### ISSUE THREAD

**Issue by Arkezis** [lapism/SearchView#4]
On 1st tap on button, the view appears but without the reveal animation.
After closing it (animation is ok), on button 2nd tap, animation is perfect.
Nexus 5, marshmallow (6.0).

See video ;-)
https://www.youtube.com/watch?v=KVMQE0nQfeU

Thanks =)

**Comment by lapism** [comment]
Oh, I see it now.  I will fix it in next release. Thanks

**Comment by lapism** [comment]
OK....I found why it is happening ... fix will be very soon.

**Comment by lapism** [comment]
It was quick fix. I hope it should be fixed now in version 1.2.1.

**Comment by americofernando** [comment]
Hi. I'm having this issue again on version 1.3.9. 
Downloading your sample project works well (compile project(':searchview')) , but when I use compile 'com.lapism:searchview:1.3.9' even on your sample project the 1st tap issue occurs.

**Comment by lapism** [comment]
Me too. It happened after pull request from someone. I will be trying to fix everything in upcoming version, but It will take some time, because I would like to do a lot of new things.

**Comment by lapism** [comment]
Should be fixed in next version.
