### ISSUE TITLE
restore SearchVIEW after running the search

### ISSUE THREAD

**Issue by Gperez88** [lapism/SearchView#40]
the method **shitOut()** can be public to restore  SearchVIEW after running the search, this if the search is performed on the same activity or a fragment example fragment Map.

**Comment by lapism** [comment]
Hi, a lot of trouble happened in last days. I somehow removed everything from Bintray and published method shitOut insted out :p. I will fix today everything.

**Comment by lapism** [comment]
2.1.1 available with public method ,,out,, :-D
