### ISSUE TITLE
Please don't remove old version from bintray

### ISSUE THREAD

**Issue by aat-antoine** [lapism/SearchView#41]
All is in the title.

I used to 1.5 but it is not available in bintray. There is only the last version 2.1 and this version breaks code

**Comment by sosite** [comment]
:+1:

Now when I try to add your lib I received a gradle error
```
Error:(112, 13) Failed to resolve: com.lapism:searchview:2.1
```
and I cannot try eg. `2.0.4` right now :disappointed:

**Comment by lapism** [comment]
Sorry for that, I accidentally removed whole repository and I need to do everything again.

**Comment by aat-antoine** [comment]
@lapism ok
@sosite You can use version from bintray if you add following code in your top build.gradle
```
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url 'https://dl.bintray.com/lapism/maven'
        }
    }
}
```

**Comment by lapism** [comment]
Oh, I did not know this way. I know those repositories are on jCenter still but I do not have them in my private maven, so I am not able to update it. I already contacted Bintray so it should be fixed ASAP.

**Comment by lapism** [comment]
And change to version 2.x, it is better :)

**Comment by aat-antoine** [comment]
For now 2.0.4 seems to be available. I am waiting 2.1.
I have updated my code with this version when it was available.

**Comment by lapism** [comment]
I will write here after Bintray version will be allowed.

**Comment by lapism** [comment]
2.1.1 available

**Comment by aat-antoine** [comment]
It's ok for me.

**Comment by lapism** [comment]
And do not worry, I am not going to change anything anytime soon ( like names of methods, etc.).
