### ISSUE TITLE
SearchBar showing when AlertDialog Showing

### ISSUE THREAD

**Issue by loaloel** [lapism/SearchView#42]
I have menu item that when it touched it will showing an alertdialog.
but when alertdialog showing, searchbar and softkeyboard showing too.
im pretty sure that im not calling SearchView.show there.
im using menu item version.
how to fix this ?
Thanks...

**Comment by lapism** [comment]
check if in your code you do not have same ids. 

            case R.id.action_search:
                .... show(true);
                return true;

Method mSeachView.show(boolean animated) works only for menu item where you have two options true / false for animation. For toolbar version it will be set as View.VISIBILE.

**Comment by loaloel** [comment]
OMG... im forgot to call return after call the method... 
i feel so stupid right now..
thanks sir...

**Comment by lapism** [comment]
it is OK :P I know this feeling...one line of the code and you are totally pissed off :P
