### ISSUE TITLE
[REQUEST] on hideKeyboard() method

### ISSUE THREAD

**Issue by Heromine** [lapism/SearchView#43]
Can you make that when the keyboard get closed the SearchView get hidden like the hide(true) method does...

**Comment by lapism** [comment]
Like both in same time?

**Comment by Heromine** [comment]
Yep

**Comment by sosite** [comment]
But of course as parameter or changeable default settings behavior or something like that.

**Comment by lapism** [comment]
Maybe in some future release, but not anytime soon.

**Comment by hardikamal** [comment]
@Heromine Did you find the solution for this??

**Comment by lapism** [comment]
Not yet. It is still in my ToDo list. You see that your issue is still open. But check test version 0.1.1. It is basic test source for next release 3.0.

**Comment by lapism** [comment]
done
