### ISSUE TITLE
[Request] SearchView input height

### ISSUE THREAD

**Issue by gnuhel** [lapism/SearchView#44]
Is it possible to set the height of the input for search view?
In my app when I am in landscape mode toolbar has a smaller height than in portrait mode. It does not looks nice.

**Comment by lapism** [comment]
do not use height of your toolbar with ?attr/actionBarSize and set it to fixed 56/64dp for normal/sw600dp. In sample app check this:
    android:layout_height="@dimen/toolbar_height"
    android:minHeight="@dimen/toolbar_height"

**Comment by lapism** [comment]
And no, it is not possible and never will be :)
