### ISSUE TITLE
[REQUEST] Add a loading icon

### ISSUE THREAD

**Issue by doppie** [lapism/SearchView#45]
Would it be possible to add a circular progress dialog in the right corner? It should overlap the voice icon.

**Comment by lapism** [comment]
Everything is possible, but why? :)

**Comment by doppie** [comment]
In my case I want to load suggestions from internet. While we are retrieving the data we want it to show a progressdialog icon so the user knows it is loading data from the internet :)

**Comment by lapism** [comment]
Ok, I will try to add something like that in next release. It is not a problem, but give me some time cause right now I am doing my diploma thesis :)

**Comment by doppie** [comment]
Got that, were can I donate?

**Comment by lapism** [comment]
Probably only here:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2W9YDH84RKA4W

**Comment by doppie** [comment]
Sure thing, I will buy you some beers for the next release party :)

**Comment by lapism** [comment]
:D thanks.

**Comment by lapism** [comment]
This function will not be a part of next version. I have done a lot of changes in library, but I do not see reason why put progress circle to library. You should use something else or do a custom version of my lib.

**Comment by Rainer-Lang** [comment]
@lapism Do you have a callback after searching is complete so the progress circle could be stopped?

**Comment by lapism** [comment]
Not now :).  In my prepared version I have these interfaces right now.

    public interface OnQueryTextListener {
        boolean onQueryTextChange(String newText);
        boolean onQueryTextSubmit(String query);
    }

    public interface OnSuggestionListener {
        boolean onSuggestionClick(int position);
        boolean onSuggestionSelect(int position);
    }

    public interface OnOpenCloseListener {
        void onClose();
        void onOpen();
    }

    public interface OnMenuClickListener {
        void onMenuClick();
    }
