### ISSUE TITLE
[REQUEST] Setting to remove the hamburger icon

### ISSUE THREAD

**Issue by doppie** [lapism/SearchView#46]
In some cases you don't have a navigationdrawer but just want the backbutton to appear.
For example when you search in Google Play store you can only go back and there is no hamburger icon.

**Comment by lapism** [comment]
I know. This is in my ToDo List and I will do it probably in next release.

**Comment by doppie** [comment]
Great to hear, keep up the good work!

**Comment by lapism** [comment]
Thanks

**Comment by lapism** [comment]
if you want to prepare for next release then test version 0.1 is uploaded to jCenter. It has some new features, but be aware that version has a lot of changes and still has some bugs.And Arrow thing is not done yet.

**Comment by lapism** [comment]
Arrow thing will be fixed in 3.0. And try test version 0.2 :).
