### ISSUE TITLE
[REQUEST] show suggestions / history with empty query

### ISSUE THREAD

**Issue by sosite** [lapism/SearchView#49]
I want to show suggestions / history right after I show `SearchView` from menu item or just click on search `EditText`. It'll be possible to add this feature?

**Comment by lapism** [comment]
Of course, but right now I will not have time for this project for maybe month. I am doing my diploma thesis.  I will add all requests ASAP.

**Comment by lapism** [comment]
Like what? String field? database?

**Comment by lapism** [comment]
Try version 0.2.
