### ISSUE TITLE
how use searchList parameter of SearchAdapter

### ISSUE THREAD

**Issue by sosite** [lapism/SearchView#50]
Does it make sense of init `SearchAdapter` with anything other than `new ArrayList<SearchItem>` as `searchList` parameter?

> lapism:
> Like what? String field? database? because if I change it for example to STRING FiELD then I will have to change recyclerView adapter as well >> more work :D.

I just don't know how to use this list - in adapter it's often cleared during filter adapter work.

If I init `SearchAdapter` with non empty `searchList` then I received
```
IndexOutOfBoundsException
at com.lapism.searchview.adapter.SearchAdapter.onBindViewHolder(SearchAdapter.java:114)
```

So maybe we don't really need to init this list itself and it will be ok to change `SearchAdapter` constructor to: `public SearchAdapter(Context context, List<SearchItem> dataList, int theme)`?

**Comment by lapism** [comment]
First list is filled with suggestions or history items. Second one is filtered list which is base of what you see on the screen...maybe it is another way how to do everything, but I will think about that later than today :)

**Comment by lapism** [comment]
New version of adapter will be in next version 3.0.
