### ISSUE TITLE
How to set Text in the Search View?

### ISSUE THREAD

**Issue by deepinder10** [lapism/SearchView#52]
I want to set the text in the search view, so that the user can edit the text before submitting if there is an error or the voice intent doesn't recognize the word correctly.I can't find anything to set the text in the sample app.

**Comment by lapism** [comment]
Text will be in next version. It is already in my custom version.

**Comment by deepinder10** [comment]
When are you planning to release next version.?

**Comment by lapism** [comment]
After I will be done with my diploma thesis :)

**Comment by deepinder10** [comment]
Wish you very best for your thesis. :)
Can i have the link to your custom version till then ?

**Comment by lapism** [comment]
After I will release it, of course ;). I will try it ASAP.

**Comment by sjtu-lyj** [comment]
i am waiting too

**Comment by lapism** [comment]
if you want then test version 0.1 is uploaded to jCenter. But be aware that version has a lot of changes and still has some bugs.

**Comment by feinstein** [comment]
Any updates on this? Can I help in anyway? :/

**Comment by HusseinElFeky** [comment]
Try getting a reference to `SearchEditText` and simply call `setText` on it.

**Comment by feinstein** [comment]
@HusseinElFeky how do I get this reference? By reflection you mean?

**Comment by HusseinElFeky** [comment]
@feinstein No need to use reflection, try to look through the search view layout and locate the `SearchEditText` so that you can get a reference to it later on by calling `getChildAt`. That should do the work temporarily.

**Comment by feinstein** [comment]
@HusseinElFeky Ok, I will try and post here any codes that work, thanks!

**Comment by feinstein** [comment]
Ok, if anyone is interested in a hack to set the text, firt get a reference to the `SearchEditText`:

    SearchEditText searchEditText = (SearchEditText) ((ViewGroup)((ViewGroup)((ViewGroup)
                    mSearchView.getChildAt(1))
                               .getChildAt(0))
                               .getChildAt(0))
                               .getChildAt(1);

and then you can set the text with:

    searchEditText.setText(text);

BE AWARE this is hack, any changes on the library will brake this code! 
I could have traversed the layout tree, nicely, checking for `instanceof` but this would have consumed me some time to code a proper traverser and have some performance impact at runtime unnecessarily.

It's a hack, while there isn't a better option coming, use at your own discretion.

**Comment by feinstein** [comment]
@HusseinElFeky Digging more into the code I found:

    public void setQuery(CharSequence query, boolean submit)
    public void setTextOnly(CharSequence text)

Why did you told me I needed to find a hack? Any problems with these methods?

**Comment by HusseinElFeky** [comment]
Actually, I haven't used the library since 2 months, so I started to forget the unused methods in the library, but yeah. As you mentioned, those methods should do the job perfectly. The ironic part is that I was the one who improved the code of `setQuery` and I forgot about that. 😂

**Comment by feinstein** [comment]
I see... Well, thanks anyways... This would have been easier with better documentation...
