### ISSUE TITLE
XML problem

### ISSUE THREAD

**Issue by mrneiverth** [lapism/SearchView#54]
Hi, 

I tried to put your searchView into my app, but when I put the xml into my toolbar, everything got as a giant as my screen. Why it happens ? how can I fix it ?

`<android.support.design.widget.AppBarLayout
        android:id="@+id/appBarLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <FrameLayout
            android:id="@+id/toolbar_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <android.support.v7.widget.Toolbar
                android:id="@+id/toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                android:background="@color/colorPrimary"
                android:title="Salas"
                app:layout_scrollFlags="scroll|enterAlways"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light">
            </android.support.v7.widget.Toolbar>

            <com.lapism.searchview.view.SearchView
                android:id="@+id/searchView"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />

            <com.lapism.check.CheckableView
                android:id="@+id/checkableView"
                android:layout_width="@dimen/fab"
                android:layout_height="@dimen/fab" />
        </FrameLayout>
    </android.support.design.widget.AppBarLayout>`

**Comment by lapism** [comment]
Check carefully sample app. Or set 56dp to height of SearchView.
