### ISSUE TITLE
Tap outside closes searchview

### ISSUE THREAD

**Issue by behelit** [lapism/SearchView#55]
I'm using the searchview to filter a listview.
How can I tap the filtered listview items if the searchview closes when I tap outside of it?

Tapping outside closes and clears the search term so the listview resets. 
Even if it didn't clear the searchview, the search term is no longer visible so it would be inappropriate to show filtered results without the using knowning a filter is applied.

Is there a way to prevent the searchview from collapsing and clearing the search term when the user taps outside of the searchview?

![Image of search filter](http://i68.tinypic.com/2mgp8on.png)

**Comment by lapism** [comment]
Workaround is to set height of SearchView to fixed 56dp and set shadow to transparent color. And new version 3.0 is on the way, but it will not be any time soon :)

**Comment by behelit** [comment]
perfect!
