### ISSUE TITLE
Library using

### ISSUE THREAD

**Issue by lapism** [lapism/SearchView#56]
Hi guys. 

Because I have done firstly this library as a private project, I would like to know if someone of you use my library in your application. If yes, please send me a name of your app and link to Play Store and I will promote your app in Readme. Thanks :)

**Comment by iAlex97** [comment]
Hello!

Thank you for developing such an awesome SearchView. I have replaced my old one and implemented your library into my app: [BCReader](https://play.google.com/store/apps/details?id=com.iac.bcreader)

**Comment by lapism** [comment]
Thanks. Your app is now in README. And next version 3.0 is coming this or next month.

**Comment by iAlex97** [comment]
Great! Looking forward to it!

**Comment by Starmel** [comment]
thanks for library
https://play.google.com/store/apps/details?id=org.super8.lastbastion

**Comment by lapism** [comment]
Awesome app ;). I will add it in Readme.
