### ISSUE TITLE
Collapse searchview with collapsingtoolbarlayout

### ISSUE THREAD

**Issue by hardikamal** [lapism/SearchView#58]
Hi Lapism,
How do i collapse the searchview with collapsing toolbar layout??

**Comment by lapism** [comment]
Probably with custom CoordinatorLayout.Behavior. Next thing in ToDo List :)

**Comment by hardikamal** [comment]
hi @lapism is this available in the test branch?

**Comment by lapism** [comment]
No yet. But I am working on it.

**Comment by ivamluz** [comment]
Hi, @lapism. Do you have any updates on this, please?

**Comment by lapism** [comment]
Hi, I did not have time for this yet. But I have to use CoordinatorLayout.Behavior or use some combination of layouts from Design Support Library.

**Comment by ivamluz** [comment]
Ok. Thanks for your inputs.

**Comment by guitcastro** [comment]
Hello,

I created I Behaviour that worked for me. I will not submit a PullRequest because I am not sure it's the best solution and I only did focusing on my Application. But I think it's a good place start :

```
package com.appprova.core.views;

import android.animation.ValueAnimator;
import android.content.Context;
import android.os.Build;
import android.support.design.widget.AppBarLayout;
import android.support.design.widget.CoordinatorLayout;
import android.support.design.widget.HeaderBehaviorHelper;
import android.support.v4.view.ViewCompat;
import android.util.AttributeSet;
import android.view.View;
import android.view.animation.DecelerateInterpolator;

import com.lapism.searchview.SearchView;

@SuppressWarnings("unused")
public class FloatingSearchViewBehaviour extends CoordinatorLayout.Behavior<SearchView> {

    private AppBarLayout appBarLayout;
    private AppBarLayout.Behavior appBarBehavior;
    private ValueAnimator valueAnimator;
    private SearchView searchView;
    private boolean isScrolling;


    @SuppressWarnings("unused")
    public FloatingSearchViewBehaviour(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public boolean layoutDependsOn(CoordinatorLayout parent, SearchView child, View dependency) {
        if (dependency instanceof AppBarLayout) {
            this.searchView = child;
            this.appBarLayout = (AppBarLayout)dependency;
            CoordinatorLayout.LayoutParams params = (CoordinatorLayout.LayoutParams)
                    appBarLayout.getLayoutParams();
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
                // A bug that makes the floating search view disappear
                appBarLayout.setStateListAnimator(null);
            }
            this.appBarBehavior = (AppBarLayout.Behavior) params.getBehavior();
            return true;
        }
        return super.layoutDependsOn(parent, child, dependency);
    }


    @Override
    public void onNestedPreScroll(CoordinatorLayout parent, SearchView child, View target,
                                  int dx, int dy, int[] consumed) {
        // We can just ignore down scroll
        if (dy >= 0 || dy > -10 || this.isScrolling) {
            return;
        }
        this.isScrolling = true;
        if (needsToAdjustSearchBar() && !isRunningAnimation()) {
            int offset = getMinExpandHeight();
            this.getValueAnimator(parent, child, -offset).start();
        }
    }

    @Override
    public void onNestedScroll(CoordinatorLayout coordinatorLayout, SearchView child, View target,
                               int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed) {
        super.onNestedScroll(coordinatorLayout, child, target, dxConsumed, dyConsumed, dxUnconsumed, dyUnconsumed);
    }

    @Override
    public void onStopNestedScroll(CoordinatorLayout coordinatorLayout, SearchView child, View target) {
        this.isScrolling = false;
    }

    @Override
    public boolean onStartNestedScroll(CoordinatorLayout coordinatorLayout,
                                       SearchView child, View directTargetChild, View target,
                                       int nestedScrollAxes) {
        return nestedScrollAxes == ViewCompat.SCROLL_AXIS_VERTICAL ||
                super.onStartNestedScroll(coordinatorLayout, child, directTargetChild, target,
                        nestedScrollAxes);
    }

    @Override
    public boolean onDependentViewChanged(CoordinatorLayout parent,
                                          SearchView child, View dependency) {
        if (needsToAdjustSearchBar()) {
            float offset = getMinExpandHeight() + appBarBehavior.getTopAndBottomOffset();
            child.setY(offset);
            return true;
        }
        return super.onDependentViewChanged(parent, child, dependency);
    }

    // Convenience

    private int getStatusBarHeight() {
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            return 0;
        }
        int result = 0;
        int resourceId = searchView.getContext().getResources()
                .getIdentifier("status_bar_height", "dimen", "android");
        if (resourceId > 0) {
            result = searchView.getContext().getResources().getDimensionPixelSize(resourceId);
        }
        return result;
    }

    private ValueAnimator getValueAnimator(CoordinatorLayout parent,
                                           SearchView searchView, int offset) {
        if (valueAnimator == null) {
            valueAnimator = ValueAnimator.ofInt();
        } else if (valueAnimator.isRunning()) {
            return valueAnimator;
        }
        valueAnimator.setInterpolator(new DecelerateInterpolator());
        valueAnimator.addUpdateListener(animation ->
                HeaderBehaviorHelper.setHeaderTopBottomOffset(parent, appBarLayout,
                        (int) animation.getAnimatedValue()));

        valueAnimator.setIntValues(appBarBehavior.getTopAndBottomOffset(), offset);
        return valueAnimator;
    }

    private boolean isRunningAnimation() {
        return valueAnimator != null && valueAnimator.isRunning();
    }

    private boolean needsToAdjustSearchBar() {
        float y = Math.abs(appBarBehavior.getTopAndBottomOffset());
        return y > getMinExpandHeight();
    }

    private int getMinExpandHeight() {
        return appBarLayout.getTotalScrollRange() - searchView.getMinimumHeight()
                -(getStatusBarHeight() / 2);
    }

}

```

**Comment by lapism** [comment]
Hi, it looks good. Right now I do not have time to maintain the library till August. So will try it ASAP. Thank you

**Comment by lapism** [comment]
@guitcastro . Hi, I do not have access to HeaderBehaviorHelper class and I did not find it in Design Library.

**Comment by cowfighting** [comment]
Hi Lapism,
is there a solution for Collapse searchview?

**Comment by lapism** [comment]
I am working on it :)

**Comment by lapism** [comment]
I will be out in version 4.0 :).

**Comment by maccam04** [comment]
any updates for this ? thanks

**Comment by lapism** [comment]
It is working with coordinator layout like in Play Store.

**Comment by lapism** [comment]
Check sample :-)

**Comment by cowfighting** [comment]
Thanks very much.

**Comment by maccam04** [comment]
its not working for me lapism. i used merge layout as a parent in my xml look what i did.

<?xml version="1.0" encoding="utf-8"?>
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/main_content"
        android:layout_width="match_parent"
        android:layout_height="match_parent">

        <android.support.design.widget.AppBarLayout
            android:id="@+id/appbar"
            android:layout_width="match_parent"
            android:layout_height="@dimen/detail_backdrop_height"
            android:fitsSystemWindows="true"
            android:theme="@style/ThemeOverlay.AppCompat.Dark.ActionBar">

            <android.support.design.widget.CollapsingToolbarLayout
                android:id="@+id/collapsing_toolbar"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true"
                app:contentScrim="?attr/colorPrimary"
                app:expandedTitleMarginEnd="64dp"
                app:expandedTitleMarginStart="48dp"
                app:expandedTitleTextAppearance="@android:color/transparent"
                app:layout_scrollFlags="scroll|exitUntilCollapsed">

                <android.support.v7.widget.Toolbar
                    android:id="@+id/toolbar"
                    app:layout_collapseMode="pin"
                    android:layout_width="match_parent"
                    android:layout_height="?attr/actionBarSize"
                    app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />


            </android.support.design.widget.CollapsingToolbarLayout>

        </android.support.design.widget.AppBarLayout>

        <android.support.v4.widget.SwipeRefreshLayout
            android:id="@+id/material_style_ptr_frame"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <android.support.v7.widget.RecyclerView
                android:id="@+id/rewardRecyclerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:clipToPadding="false"
                android:scrollbars="vertical" />

        </android.support.v4.widget.SwipeRefreshLayout>

    </android.support.design.widget.CoordinatorLayout>


    <com.lapism.searchview.SearchView
        android:id="@+id/newSearchView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_collapseMode="pin" />

</merge>

i dont think if it's best approach to inflate searchview while collapsing toolbar.
