### ISSUE TITLE
make typed bold

### ISSUE THREAD

**Issue by Rainer-Lang** [lapism/SearchView#6]
If the user types letters in search field it would be really nice that these letters are bold in the suggestion list.
That would be nice ux.

**Comment by lapism** [comment]
ok, thanks for idea. I will add it asap.

**Comment by lapism** [comment]
Right now I am working on it. It will look like Google Play Store and that improvement will be in version 1.3.2.

**Comment by Rainer-Lang** [comment]
Great!

**Comment by lapism** [comment]
Done with 1.3.2.

**Comment by Rainer-Lang** [comment]
Works. Thank you.
