### ISSUE TITLE
Fix icon colors

### ISSUE THREAD

**Issue by julianostarek** [lapism/SearchView#62]
Could you please fix the icon colors in the light, classic menuitem theme. Those are #000000 but should be 54% black (#8a000000) as of the guidelines

**Comment by lapism** [comment]
Of course, but from next version you will be able to set custom color. I have already this function in my repo, but it is not done yet. But you can try 0.1.4 , it is alpha version for next release.

**Comment by lapism** [comment]
Fixed in 0.2.
