### ISSUE TITLE
[REQUEST] Set / get Custom Item on Suggestion List when user typing 

### ISSUE THREAD

**Issue by Gujarats** [lapism/SearchView#63]
Hi thank you for writhing this awesome library it helps me to build faster on my project. Okay now get to the point :)..  I want to pass object information in the suggestion list and get that value like, username, title, id, and imageUrl. 

So I've made some changes on the adapter for the suggestion result when user typing on the search field, it turns out I must change other class too and copying the classes (most of them to my folder project), I just wondering if we can add custom Item in the SuggestionAdapter so I can easily add my custom Item to the suggestion list. and the get the selected item value when user click on the Suggestion list.

I've finished the feature and I just curious about this so I ask here so maybe I can get more code suggestion, thank you.

**Comment by lapism** [comment]
Hi, thank you. Next version of the library will have a lot of changes and I will try to fix every bug. But if you want to change the item of RecyclerView then you need custom adapter cause I have some important things like filtering database in the adapter. But I will consider to do some BaseAdapter class which you can extend and do some custom changes. Btw, that is a nice idea :D

**Comment by Gujarats** [comment]
Cool that's awesome, I'm glad giving you a nice idea.

**Comment by skunkfu2** [comment]
+1

**Comment by lapism** [comment]
I am not really sure how to do it now, but I will try ASAP.

**Comment by lapism** [comment]
Right now I do not have time for BaseAdapter and things like that. Sorry guys. 
But I hope I will finish release 3.0 soon.
