### ISSUE TITLE
Show Suggestion Search Item Multiple text

### ISSUE THREAD

**Issue by JazminGuo** [lapism/SearchView#64]
Hi, I want to ask some question, It is posible in the SearchItem can show Multiple Text?
For emxpamle;

Text 1, Text 2

**Comment by lapism** [comment]
No, only with custom RecyclerView Adapter. So you can use the library but you have to do your own implementation of adapter with library version as its base.

**Comment by JazminGuo** [comment]
And why I can't find some xml in my projetc like search_item, which in SearchAdapter class, in method ResultViewHolder? It because the library include it?

**Comment by lapism** [comment]
yes. Check the code here and you will see it.

**Comment by JazminGuo** [comment]
And How can I close or dispare the RecyclerView (List View) when I selected the Item?

**Comment by JazminGuo** [comment]
Sorry again, I have some questions about the search view with suggestion, can you help me or give me some tips please?

                 Suggestion
---------------------------------------------
|___Company1, Product 1_______|
|___Company2, Product 2_______|
|___Company3, Product 3_______|

I want to make a search view with suggestion with multiple text, but the purpose final is when I selected the Item, I want to get the name of the Company 1 and name of the Product 2, because I need these name to consult to Web Service. 
So for moment I have no idea how to implement it with your code.

**Comment by lapism** [comment]
you can't  do it with my code cause you need to implement your own adapter. My adapter has SearchItem with imageview and textview. So copy SearchAdapter and change what you want and then use it with SearchView Library.

**Comment by JazminGuo** [comment]
Yes, I had copy the SearchAdapter and I add a new textview in ResultViewHolder class, and I had copy the SearchItem, and in the constructor I add new parameters like this:

     public SearchViewItem(CharSequence text1,CharSequence text2) {
        this(text1,text2, R.drawable.search_ic_search_black_24dp);
    }

    public SearchViewItem(CharSequence text, CharSequence text2,int icon) {
        this.icon = icon;
        this.text = text;
        this.text2 = text2;
    }

But the problem is, when I run the app, and I type something for example "Google", the suggestion is showing the search icon but the letter is blank. I think I need to do something in the class SearchView, but I don´t know how.
