### ISSUE TITLE
Great library but crashes too often

### ISSUE THREAD

**Issue by Shailevy** [lapism/SearchView#68]
Hi, 
I really like you library and I started using it in a pretty popular App.
After enrolling 0.5% of my users I start seeing crashes in crashlytics.
Some of them I just surrounded with try+ctach but others happen in the adpter and not in my call-stack so I can't propperly catch them without download and recompiling your source code.

I couldn't find version 0.3 source code and it's pretty intimidating to work with an early beta so I'm not sure what should be my next step.

Feel free to contact me to discuss further

![image](https://cloud.githubusercontent.com/assets/254902/15110191/28975a3c-15e8-11e6-9222-1b3a824c0162.png)

**Comment by lapism** [comment]
Hi, which version are you using? I am almost done with next 3.0 version. And 0.3 test source is not out, cause I was doing a log of changes every day.

**Comment by Shailevy** [comment]
I"m using 2.2
Do you recommend I switch to 3.0 (from jcenter)?

**Comment by lapism** [comment]
Yes, of course. For you, I will upload 0.4. It is almost finished version. But you will have to change names of a few methods, nothing complicated. Feel free to contact me here.

**Comment by lapism** [comment]
And 2.2 has adapter bug.

**Comment by Shailevy** [comment]
Great, so let me know when 0.4 is is accessible in jcenter or elsewhere ?

**Comment by lapism** [comment]
Instead test version 0.4 I decided to upload version 3.0 :)). And it is already on jCenter.

**Comment by Shailevy** [comment]
Great, I will use that to continure the stages roll-out withou changing you code. closing the issue

**Comment by lapism** [comment]
This issue will be open for others. And if you will find some bug, please let me know. Thanks.

**Comment by Shailevy** [comment]
Great
You should probably fix the documentation to com.lapism.searchview.SearchView (from com.lapism.searchview.view.SearchView )

**Comment by lapism** [comment]
Oh...thanks :p. I will have to fix many things in documentation. Because you needed new version I released 3.0 earlier, so it is not done yet.

**Comment by lapism** [comment]
Version 3.0.1 is released.
