### ISSUE TITLE
problems to integrate the lib

### ISSUE THREAD

**Issue by Rainer-Lang** [lapism/SearchView#7]
First: I use the MaterialDrawer https://github.com/mikepenz/MaterialDrawer
In my layout file I don't have any DrawerLayout.

I also use a ViewPager.

---------------------
If I tap on the icon in the toolbar - the whole screen is darkened but noting else shown. If I tap again on the screen then all changed back to normal.

**Comment by lapism** [comment]
Hi, I know this library and it is awesome work. But I have never tried it so I am not really sure how it works. But it is trivial to use it in different layout. Try this

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".SearchActivity">

        <LinearLayout
            android:orientation="vertical"
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <include layout="@layout/toolbar" />

            <ScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:contentDescription="@string/cont_desc"
                    android:src="@drawable/logo" />

            </ScrollView>
        </LinearLayout>

    <com.lapism.searchview.SearchView
        android:id="@+id/search_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent" >

    </com.lapism.searchview.SearchView>

</FrameLayout>

**Comment by lapism** [comment]
Hi, I know this library and it is awesome work. But I have never tried it so I am not really sure how it works. But it is trivial to use it in different layout. Try this: http://pastebin.com/Fs4beQbk

**Comment by Rainer-Lang** [comment]
Mike (MaterialDrawer) helped me. Now it works. :-)
He put a FrameLayout around all.

I close the issue.

**Comment by lapism** [comment]
And I have done some thing :).

**Comment by Rainer-Lang** [comment]
Mike and you did the same. :-)
