### ISSUE TITLE
The hamburger icon is blurry

### ISSUE THREAD

**Issue by EpsilonOrionis** [lapism/SearchView#71]

**Comment by lapism** [comment]
Please do not open three issues. Which version Android are you using ?

**Comment by EpsilonOrionis** [comment]
Lollipop, why can't I open three issues?

**Comment by lapism** [comment]
Feel free to do whatever you want to do, but if you have three issues as one person then better is open one issue with those problems. Cause maybe it depends on device, version of your Android OS etc. In library you can change many things, but blurry issue probably means use of AccelerateDecelerateInterpolator. I will fix it in next version.

**Comment by EpsilonOrionis** [comment]
Ok so, regarding the problem about the adapter that doesn't return any suggestion, your response was: "See the example. you'll see". I'm using your code, but nothing happens

**Comment by lapism** [comment]
Now I see you are totally right. I am going to check it.

**Comment by EpsilonOrionis** [comment]
Thank you :)

**Comment by lapism** [comment]
Please use 3.0.1 and let me know :). Suggestions must be like this:

            List<SearchItem> suggestionsList = new ArrayList<>();
            suggestionsList.add(new SearchItem("Blue"));

            SearchAdapter searchAdapter = new SearchAdapter(this, suggestionsList);

**Comment by EpsilonOrionis** [comment]
I'm trying right now

**Comment by EpsilonOrionis** [comment]
No, it isn't working

**Comment by lapism** [comment]
Try to search something and your suggestions will be there after searching. It is a bug and I will fix it in next version in next days.

**Comment by EpsilonOrionis** [comment]
Tomorrow?

**Comment by lapism** [comment]
Now :D wait five minutes.

**Comment by lapism** [comment]
Ok, it is going to take a while....:/

**Comment by lapism** [comment]
It should be fixed in new 3.0.1. Damn.

**Comment by EpsilonOrionis** [comment]
So?

**Comment by lapism** [comment]
try it :D

**Comment by EpsilonOrionis** [comment]
No, nothing happens

**Comment by lapism** [comment]
Clean the dependency in gradle file, sync the project and add it again and then sync again.
You are using old one.

**Comment by EpsilonOrionis** [comment]
The sample app in the Google Play Store is working as it is supposed to do?

**Comment by lapism** [comment]
Yes. Version from Play Store has last version of the library on jCenter.

**Comment by EpsilonOrionis** [comment]
Is the issue solved?

**Comment by lapism** [comment]
For me yes. Last version is 3.0.1, but it has changes from previous 3.0.1. Check Play Store version and try to search ,,search,,

**Comment by EpsilonOrionis** [comment]
Ok
