### ISSUE TITLE
[REQUEST] Keep searched term on close

### ISSUE THREAD

**Issue by tkskoapps** [lapism/SearchView#72]
Hi!

I am filtering a list while user is typying, but when the searchView closes, the search is cleared and the list filter restarts...

It would be great if you add the posibility to keep the current search when the user click on the magnifier and then click outsite the toolbar (close the searchView) and then click on the magnifier again..

I dont know if i am clear... 

thanks for your time and your great work! your searchview is awesome!

P.D:  I am using the VERSION_MENU_ITEM version with shadows (R.color.search_shadow_layout).

**Comment by lapism** [comment]
Thanks. I understand what you mean...I will try to add this feature in next version. Good idea btw.

**Comment by lapism** [comment]
Scheduled for future release 3.3.

**Comment by couchcrew-thomas** [comment]
I will take care of this. I'm planning to add a boolean attribute to toggle if the query should be cleared or not. I think I'll be able to submit the PR today or on monday.

**Comment by lapism** [comment]
Super, because I do not have time to do changes every day. Please fork last version of the project because it is prepared version for 3.3.

**Comment by couchcrew-thomas** [comment]
The query is not cleared anymore in 3.3.
Did you already fixed it or is it a side effect of changes for 3.3?

**Comment by lapism** [comment]
Yes, I have changed something in adapter ;).

**Comment by couchcrew-thomas** [comment]
Well then there's no bug anymore from my side. Because currently the active query stays inside the EditText as it should.
I could still add an option to define the behaviour, but if someone wants the query to clear, setting it to an empty string would work now, as well.
What do you think? Would an option still be required?

**Comment by lapism** [comment]
I think now it is OK. I do not wanna add more  and more things now. Main thing are bugs ;)

**Comment by ivamluz** [comment]
What's the expected behavior here?

I tested it and this is the behavior I see:
- Search view gets closed;
- Search view shows the hint text (not the searched term);
- When I open the search view again, the suggestions are still there, but the text in the search view gets lost.

**Comment by lapism** [comment]
I think expected behavior is to be like Play Store exactly :D.

**Comment by ivamluz** [comment]
Hahaha, makes sense, @lapism. My question was more of what to expect of the component now, since @couchcrew-thomas mentioned he sees no bug anymore and I found this weird behavior I described previously.

**Comment by lapism** [comment]
Maybe I should check whole library and match it with Play Store. But right now I do not have time for this and I will in August.

**Comment by ivamluz** [comment]
I understand and appreciate it, @lapism. I'll submit a pull request for any change I make so I may help you.

**Comment by lapism** [comment]
It will be awesome. Thank you very much.

**Comment by ivamluz** [comment]
@lapism, it seems I forgot to perform the check inside the animations to open/close. Gonna update my pull request soon.

**Comment by lapism** [comment]
Ok. I am not going to release it yet :))

**Comment by ivamluz** [comment]
@lapism, hasn't this been released yet?

**Comment by lapism** [comment]
I have been waiting for updates of Android N and they have been released yesterday so next version with all of your pull requests will be tomorrow.

**Comment by ivamluz** [comment]
Got it. Thanks for the update.
