### ISSUE TITLE
setElevation does not work in runtime(dynamically)

### ISSUE THREAD

**Issue by mohsenht** [lapism/SearchView#74]
hi lapism

i think that if you change below code

@Override
    public void setElevation(float elevation) {
        mCardView.setCardElevation(elevation);
    }
in your SearchView class

to this

@Override
    public void setElevation(float elevation) {
        mCardView.setMaxCardElevation(elevation);
        mCardView.setCardElevation(elevation);
    }

this issue will be correct

**Comment by lapism** [comment]
Your totally right. Bug :). I will add it to next version. Thanks.

**Comment by lapism** [comment]
And in code...try to set mSearchView.invalidate().

**Comment by lapism** [comment]
Fixed in 3.0.2.
