### ISSUE TITLE
Back arrow color

### ISSUE THREAD

**Issue by EpsilonOrionis** [lapism/SearchView#75]
The icon color remains #212121, you said to change icon color: mSearchView.setIconColor(int color), but it changes the color of the microphone icon. Any suggestions?

**Comment by lapism** [comment]
Are you using 3.0.2? If not I will take a look on it later.

**Comment by lapism** [comment]
mSearchView.setIconColor(ContextCompat.getColor(this, android.R.color.holo_orange_dark));
For example. And do not use Theme after it.

**Comment by EpsilonOrionis** [comment]
Android Lollipop it isn't working.

 mSearchView = (SearchView) findViewById(R.id.searchView);
        mSearchView.setDivider(true);
        mSearchView.setHint("Search");
        mSearchView.setIconColor(ContextCompat.getColor(this, R.color.material_red));
        mSearchView.setVoice(true);
        mSearchView.setShadow(true);
        mSearchView.setVersion(SearchView.VERSION_MENU_ITEM);
        mSearchView.setVersionMargins(SearchView.VERSION_MARGINS_MENU_ITEM);
        mSearchView.setTextSize(16);
        mSearchView.setVoice(true);
        mSearchView.setAnimationDuration(SearchView.ANIMATION_DURATION);
        mSearchView.setVoiceText("Tocca per parlare");
        mSearchView.setShadowColor(ContextCompat.getColor(this, R.color.search_shadow_layout));

Do you see anything wrong?

**Comment by lapism** [comment]
Nothing. I have device with KitKat, so I am going to try this. Till then you should use default Theme colors.

**Comment by EpsilonOrionis** [comment]
Let me know :)

**Comment by lapism** [comment]
setVersion before setIconColor...

**Comment by EpsilonOrionis** [comment]
Ok, everything works now
