### ISSUE TITLE
[Ask] How to use ONClick ListSuggestion Item

### ISSUE THREAD

**Issue by caheovista** [lapism/SearchView#76]
I want to setOnClick Item in ListSuggestion to new Intent. How can i do it.
Thanks

**Comment by lapism** [comment]
I do not understand to language of your tribe. I am kidding :). 
Everything you can find in sample project in BaseActivity. 

            searchAdapter.setOnItemClickListener(new SearchAdapter.OnItemClickListener() {
                @Override
                public void onItemClick(View view, int position) {
                    mSearchView.close(false);
                    TextView textView = (TextView) view.findViewById(R.id.textView_item_text);
                    String query = textView.getText().toString();
                    getData(query, position);
                }
            });

**Comment by caheovista** [comment]
Thanks. I just learning nearly.
