### ISSUE TITLE
[REQUEST] result to suggestion list

### ISSUE THREAD

**Issue by N1cE174** [lapism/SearchView#79]
I use `onQueryTextChange` for web reques and when I'll got response how to replace current suggestion list (or SearchAdapter) to new list (or Adapter) from response?

I tried use ` mSearchView.setAdapter(new searchAdapterFromResponse)` but after request success dropdown suggestions list just hide

Mb you'll add method for Search Adapter that will update suggestion array list?
Or change in [SearchView.java](https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchView.java#L617)
```
public void setAdapter(SearchAdapter adapter) {
        mSearchAdapter = adapter;
        mRecyclerView.setAdapter(mSearchAdapter);
    }
```
to 
```
public void setAdapter(RecyclerView.Adapter adapter) {
        mSearchAdapter = adapter;
        mRecyclerView.setAdapter(mSearchAdapter);
    }
```
for using custom adapter.

Or tell me better solution without changing lib sources

**Comment by lapism** [comment]
HI, I will add static methods getSuggestions and setSuggestions to SearchAdapter in next release. In think it is the best way ho to do it. But right now I will not be able to do it in next two weeks cause I am not at home.

**Comment by N1cE174** [comment]
Ok, I'll wait ty

**Comment by N1cE174** [comment]
Mb u'll add subtitle for items in suggestions like this
![screenshot_20160523-173947](https://cloud.githubusercontent.com/assets/8428514/15471100/ac0f360c-210d-11e6-9d5f-59a5c842cb7e.png)

And create method satTag for title` textView` that will setting and response custom object.
Sample:
In any Activity or fragment
```
ArrayList<SearchItem> suggestionsList = new ArrayList<>();
suggestionsList.add(new SearchItem((String)title, (String)subtitle, (object)custom, (int)icon))
```
and in `SearchAdapter` below [setting text for item](https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchAdapter.java#L122)
```
        if(item.getTag()!=null) {
            viewHolder.text.setTag(item.getTag());
        } else {
            viewHolder.text.setTag(null);
        }
```
And in `searchAdapter.setOnItemClickListener` we can use custom object for item like this:
```
TextView textView = (TextView) view.findViewById(R.id.textView_item_text);
                ((CustomObject)textView.getTag()).itemID
```

But better solution is change [this Line](https://github.com/lapism/SearchView/blob/master/searchview/src/main/java/com/lapism/searchview/SearchView.java#L617)
to `public void setAdapter(RecyclerView.Adapter adapter)` for attaching custom SearchAdapter for advanced users

**Comment by lapism** [comment]
Ok, I will check it in next version. Thanks.

**Comment by lapism** [comment]
Btw. Nice app ;)

**Comment by lapism** [comment]
Oh...its play store :-D

**Comment by N1cE174** [comment]
Ty again. I'll wait update.
And no, it's no gp, it's my app for movies)

**Comment by lapism** [comment]
Looks very good. I can add your app to Readme after you will release it with my lib.

**Comment by smiderle** [comment]
When it wil be released ,the new release with Update suggestion, ?

**Comment by lapism** [comment]
Next week after my last university exam.

**Comment by lapism** [comment]
Fixed for next release.

**Comment by birijan** [comment]
Thanks for update, this is nice once and simple. I saw setAdapter(RecyclerView.Adapter adapter) that is commented on updated SearchView.java. For complete customisation of layout change for results, can it be enabled please?

public void setAdapter(RecyclerView.Adapter adapter) {
        mSearchAdapter = adapter;
        mRecyclerView.setAdapter(mSearchAdapter);
   }

Thanks. Hope to hear you soon.

**Comment by lapism** [comment]
Hi. It will be in next version because I need to change more things than this method. This week probably,

**Comment by birijan** [comment]
Eagerly waiting for this feature to be added. Thanks a lot.

**Comment by lapism** [comment]
Added for next release.
