### ISSUE TITLE
compile 'com.lapism:searchview:2.1.1'  ,This library is not valid!

### ISSUE THREAD

**Issue by Arisono** [lapism/SearchView#80]
Introduced version 2.1.1; in Studio Android compile, can not find this version;but, the version 2.2 is ok! Hope can get a short explanation！please！

**Comment by lapism** [comment]
Use 2.2. But you should change to 3.0.2 and check sample project because version 3.x has some changes.

**Comment by lapism** [comment]
2.1.1 and 2.2 have bugs.

**Comment by Arisono** [comment]
Thank you very much for your help!

**Comment by lapism** [comment]
You are welcome ;)
