### ISSUE TITLE
Is there any way to use this search view as a normal view?

### ISSUE THREAD

**Issue by WrathChaos** [lapism/SearchView#83]
Hello,
I love your work but i want to use this as a normal view not on my toolbar and my onCreateOptionsMenu. Is there any way or chance to use it. 

If the answer is yes, can you create a little example for me?

**Comment by lapism** [comment]
Hi, you can use toolbar vetsion. In code mSearchView.setVersion(SearchView.VERSION_TOOLBAR) or in Xml app:search_version="toolbar". Everything is in example project ;).
