### ISSUE TITLE
[REQUEST] Version Toolbar should display hamburger menu item optionally

### ISSUE THREAD

**Issue by wbervoets** [lapism/SearchView#85]
Hello,

In Google Play Store when one searches an App in eg subcategory Games, you'll get a SearchView of type Toolbar. It doesn't however show a hamburger menu item (because there is no sidebar menu); only a back arrow.

Is this functionality supported in your library?

Thanks
Wim

**Comment by lapism** [comment]
Method setArrow and setHamburger will be available in next release which will be out next week probably.

**Comment by lapism** [comment]
Scheduled for future release 3.3.

**Comment by wbervoets** [comment]
thanks, I see that there is a new version 3.2 - Can you provide a changelog what has changed since 3.0?

Wim

**Comment by lapism** [comment]
Nothing important, only fixes and RTL support. But from next version I will do a changelog for every version. People should now what has been changed...

**Comment by lapism** [comment]
Scheduled for future release 3.3.

**Comment by couchcrew-thomas** [comment]
I'm also missing this feature. It would be great if the icon of the left buttom could be customized.

**Comment by lapism** [comment]
Ok, I will add it to next version :)

**Comment by lapism** [comment]
Scheduled for future release 3.3.

**Comment by lapism** [comment]
Added in 3.3.

**Comment by wbervoets** [comment]
Thanks for the new feature :-)

I tried upgrading and everything is working. One question => why is the mEmptyImageView not available when using the version VERSION_TOOLBAR_ICON?

Thanks
Wim

**Comment by lapism** [comment]
What you mean exactly?

**Comment by lapism** [comment]
And you are welcome :-)

**Comment by wbervoets** [comment]
Hi,

When using VERSION_TOOLBAR_ICON, the icon on the right is always the Voice search icon. With VERSION_TOOLBAR it changes to the X icon (mEmptyimageView) when the search field gets focus.

I think it would also be nice when the user is able to clear the text field when using VERSION_TOOLBAR_ICON.

I also noticed that the OnOpenCloseListener onOpen/onClose is only called when using VERSION_TOOLBAR, not when using the similar VERSION_TOOLBAR_ICON. Is this a bug or done by design?

Thanks
Wim

**Comment by lapism** [comment]
oh, you are right. Those are bugs. I forgot to change and add something, but fix is very very simple. I will release today or tomorrow 3.3.1.

**Comment by wbervoets** [comment]
In my locally modified version I also added:

 showClearTextIcon(); inside addFocus()
hideClearTextIcon(); inside removeFocus()

private void hideClearTextIcon() {
        mEmptyImageView.setVisibility(View.GONE);
        checkVoiceStatus(true);
    }

private void showClearTextIcon() {
        mEmptyImageView.setVisibility(View.VISIBLE);
        checkVoiceStatus(false);
    }

In onClick(View v) I also added setHint(""): (to make sure that when text is cleared the hint is also gone (if it was set)



} else if (v == mEmptyImageView) {
            if (mEditText.length() > 0) {
                mEditText.getText().clear();
            }
            setHint("");
        }

**Comment by lapism** [comment]
Thanks. I will try to put it to next release.

**Comment by wbervoets** [comment]
thanks, looking forward to the next release

**Comment by wbervoets** [comment]
For your info I updated my modified version:

private void hideClearTextIcon() {
        if (mUserQuery.length() == 0) {
            mEmptyImageView.setVisibility(View.GONE);
            checkVoiceStatus(true);
        }
    }


private void showClearTextIcon() {
        if (mUserQuery.length() > 0) {
            mEmptyImageView.setVisibility(View.VISIBLE);
            checkVoiceStatus(false);
        }
    }

This way the Voice search icon stays visible when there is no text inside the search field

**Comment by lapism** [comment]
ASAP. ;). Next week probably.

**Comment by lapism** [comment]
Version 3.3.2 is out with your changes. Please next time send me a pull request.
