### ISSUE TITLE
[REQUEST] hamburger icon animates wrongly in right to left layouts

### ISSUE THREAD

**Issue by mohsenht** [lapism/SearchView#86]
hi lapism

hamburger icon animates wrongly in rtl layouts, i'm developing multi-language app that should displays layouts from right to left in right to left languages and i'm using your great library.

**Comment by lapism** [comment]
Oh, sorry I did know that cause I am from Europe :-). So I what I should change in next release ? Version 3.1 will be out next week probably.

**Comment by lapism** [comment]
Fixed for next release.
