### ISSUE TITLE
[REQUEST] OnArrowClickListener ala OnMenuClickListener

### ISSUE THREAD

**Issue by Rainer-Lang** [lapism/SearchView#87]
I need an OnArrowClickListener to get the click on the arrow.

I have a completely separate search activity. While starting the activity I open the searchview in the toolbar.
To close the search activity I want to use the arrow.

OnOpenCloseListener::onClose() - is not working, because the SearchView has at first no focus.

Thanks.

**Comment by lapism** [comment]
Hi, next week I will have finally time for this. And I will add it ASAP. But of course I am open for every pull request :-P

**Comment by lapism** [comment]
Scheduled for future release 3.3.

**Comment by lapism** [comment]
Added in 3.3 with VERSION_TOOLBAR_ICON.

**Comment by Rainer-Lang** [comment]
@lapism Sorry didn't find it. Could you please give me a hint?

**Comment by lapism** [comment]
just use VERSION_TOOLBAR.

**Comment by Rainer-Lang** [comment]
@lapism Thanks. I use now ```mSearchView.setArrowOnly(false);``` to only show the back arrow and not the hamburger icon. So for me all works now.

**Comment by lapism** [comment]
I am happy to hear that.
