### ISSUE TITLE
Hi , is the onClose , onOpen function called properly?

### ISSUE THREAD

**Issue by cuikangyuan** [lapism/SearchView#88]
Hi ,
 when i use the library, i add the search view in activity, but when i get in this activity, i write searchView.open()  so we can input , at the mean time , i also want this activity to finish when the search view close, so the code is like this

```java
mSearchView.setOnOpenCloseListener(new SearchView.OnOpenCloseListener() {
                @Override
                public void onOpen() {

                }

                @Override
                public void onClose() {
                    SearchActivity.this.finish();
                }
            });
```
but in fact , when i get in this search activity , it will call onOpen function, then the onClose function is called too , so the activity is finished at once , but i only call 
```java
mSearchView.open(true);
```
how to solve that problem?

**Comment by lapism** [comment]
I will check this ... if it is a bug then fix will be soon.

**Comment by ntsik** [comment]
Can confirm that this is not working as expected.

Looking into the source, it appears to be an issue with SearchView.initView and SearchAnimator. Specifically, SearchView.mSearchAnimator is only ever created in SearchView.initView, which is only called from the constructors (where mOpenCloseListener is always null). Therefore, whenever SearchView.setOnOpenCloseListener is called, the listener is never actually set into the SearchAnimator.

**Comment by lapism** [comment]
You are right. Fix will be available in next version. I hope :).
