### ISSUE TITLE
No requestFocus() for SDK_INT < LOLLIPOP

### ISSUE THREAD

**Issue by oleynikd** [lapism/SearchView#89]
Hi,

 Thanks for such a great tool!

I have an issue on < LOLLIPOP! After calling `open(true)` search `EditText` is not focusing!
I guess it's because `mEditText.requestFocus();`[ is never called](https://github.com/lapism/SearchView/blob/76a4e4951f453db6fed1cbf8bcc90197a4f8ff61/searchview/src/main/java/com/lapism/searchview/SearchView.java#L558-L562) if `animate` is `true`...

Is it the expected behaviour?

**Comment by lapism** [comment]
Hi, I know about that. It has // TODO in project code and will be fixed next week in next version.

**Comment by lapism** [comment]
Fixed for next release.
