### ISSUE TITLE
How to hide the Voice icon ? 

### ISSUE THREAD

**Issue by brucezz** [lapism/SearchView#9]
`searchView.showVoice(false);` it doesn't work.

**Comment by brucezz** [comment]
It's my first time to write the issue.I just want to look for some help :) 
Thanks.

**Comment by lapism** [comment]
Hi, try setVoiceSearch(false) ;)

**Comment by lapism** [comment]
and showVoice should be private ;).

**Comment by brucezz** [comment]
I just upgrade your library to version 1.3.2, then use the new APIs.  problem solved!

thanks!
