### ISSUE TITLE
close search on keyboard close

### ISSUE THREAD

**Issue by skonstant** [lapism/SearchView#90]
Hi I noticed the search does not clos on keyboard close, so I made a little fork:

https://github.com/skonstant/SearchView

also, I removed all the pngs and use vecotr drawables instead, feel free to integrate this fork.

Thanks

**Comment by lapism** [comment]
Hi, could you send me a pull request? Thanks.

**Comment by lapism** [comment]
Thanks. I am going to integrate these changes to the library.
