### ISSUE TITLE
SearchEditText needs more padding or should match_parent

### ISSUE THREAD

**Issue by EdwardvanRaak** [lapism/SearchView#93]
The SearchEditText feels too small to press because the height is set to wrap_content. 

Not being able to press slightly lower or higher of the SearchEditText feels clunky because you are still pressing inside the area of the SearchView yet it's ignoring the press. The same applies to the buttons left/right.

The playstore searchview does not have this problem and it should be an easy fix.

**Comment by lapism** [comment]
I am going to fix it to next version. thanks

**Comment by lapism** [comment]
Should be fixed in next version.
