### ISSUE TITLE
Release notes/Upgrade guide

### ISSUE THREAD

**Issue by alashow** [lapism/SearchView#94]
Hello.

I like your library but could you please write release notes/upgrade guide for each new version?
Because every time I upgrade version I'm struggling to resolve many errors. You change method names, remove methods, refactor packages, remove/add features, changing visibility of methods. And I, struggle to resolve them, browsing sample app to know how to do it new version. I'm sure I'm not the only who.

I hesitate to upgrade to new version, because each time when I upgrade my app won't compile with the same code, my code will break.

For example, in 3.2 (I was in 3.0.2) I couldn't find alternative for `SearchHistoryTable.getAllItems()` , because you changed visibility (I think it was public before, now it's not accessible).

Or when I upgraded from 2.2 to 3.2, you changed a lot of things. Moved classes, changed method names (show->open,hide->close), removed some xml attrs etc.

So, If you write something like Release notes, or upgrade guides, it will be easy to see what's new, easy to upgrade.

Thank you!

**Comment by lapism** [comment]
Hi, you are totally right.I will do it from next version. Sorry for these changes but release 3.0 was major change of the library and now I will not change anything important ( names, ...etc.). Method getAllItems is local because I use it only in SearchView class. I did not know that someone use it somewhere else. I am going to change the visibility right now .... especially for you.

**Comment by lapism** [comment]
3.2.1 is out.

**Comment by alashow** [comment]
Thanks!

Yes. I was using `SearchHistoryTable.getAllItems()` to show old queries. Similar implementation was in 2.x (`mSuggestionsList.addAll(searchHistoryTable.getAllItems());`), isn't it?
Is adding queries from history to suggestions list changed now? How to add them 3.x.x?

**Comment by lapism** [comment]
Now you can set suggestions through constructor or through method. Both in adapter.
