### ISSUE TITLE
From version 3.2 SearchAdapter.ResultViewHolder isn't public anymore

### ISSUE THREAD

**Issue by ultraon** [lapism/SearchView#96]
Hello Martin, after changes you added from version 3.2 the SearchAdapter.ResultViewHolder, and this change breaks the ability to extend SearchAdapter and adding new ResultViewHolder implementations (different item layout). Could you please revert public modifier for this class?

**Comment by lapism** [comment]
Damn.Sorry, I forgot...use 3.2.2.

**Comment by ultraon** [comment]
I tried to update dependencies with version 3.2.2, but i have the same issue. May be you need to deploy new version or increment version name (e.g. 3.2.3)?

**Comment by ultraon** [comment]
I've got simultaneous issue with SearchItem.get_icon(), SearchItem.get_text(), they was a public, and now they are private-package :-( What was the reason to change them?

**Comment by lapism** [comment]
Automatic lint check. I will change it today.

**Comment by lapism** [comment]
Yes ;).

**Comment by lapism** [comment]
3.2.3 for you

**Comment by ultraon** [comment]
Hello, Martin! Great news, thank you so much!!!

**Comment by lapism** [comment]
You are welcome :)
