### ISSUE TITLE
Could not find com.lapism:searchview:3.2.3.

### ISSUE THREAD

**Issue by HanderWei** [lapism/SearchView#98]
```
Error:Could not find com.lapism:searchview:3.2.3.
Required by:
    SuzhouBus:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

**Comment by lapism** [comment]
Soon will be available...I had to delete this version because there was an error in upload.

**Comment by HanderWei** [comment]
@lapism Thanks!

**Comment by ultraon** [comment]
+1 Still needed 3.2.3 :-)

**Comment by lapism** [comment]
I know. It will be back with 3.3. Changes are already in repository. After I fix one thing I will release it.

**Comment by lapism** [comment]
3.3 is out guys. I hope now without new bugs :D
